[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags =
    -DCORE_DEBUG_LEVEL=1
lib_deps =
    bblanchon/ArduinoJson@^7.0.4
    crankyoldgit/IRremoteESP8266@^2.8.6
    links2004/WebSockets@^2.4.1
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14
