ManualContent.registrar([
  {
    id: "selecao-sala",
    titulo: "Selecionar bloco, andar e sala",
    categoria: "salas",
    tags: ["cards", "lista", "planta baixa", "bloco", "andar"],
    verNoApp: "/salas",
    corpo: [
      { t: "p", texto: "<strong>Salas</strong> oferece três formas equivalentes de chegar ao painel: <strong>Cards</strong>, <strong>Lista</strong> e <strong>Planta baixa</strong>. Escolha a que facilita reconhecer o ambiente; todas usam os mesmos dados." },
      { t: "fluxo", titulo: "Caminhos equivalentes", itens: [
        { tipo: "screen", texto: "Salas" },
        { tipo: "decision", texto: "Cards · Lista · Planta baixa" },
        { tipo: "action", texto: "Bloco e andar, quando solicitado" },
        { tipo: "screen", texto: "Painel da sala" },
      ] },
      { t: "sub", titulo: "Cards e Lista" },
      { t: "passos", itens: [
        "Abra <strong>Salas</strong> e selecione <strong>Cards</strong> ou <strong>Lista</strong>.",
        "Escolha o bloco e o andar apresentados.",
        "Identifique a sala pelo código e nome; confira conexão, ligado/desligado, reserva e indicação de visualização.",
        "Selecione a sala para abrir o painel.",
      ] },
      { t: "sub", titulo: "Planta baixa" },
      { t: "passos", itens: [
        "Abra <strong>Planta baixa</strong> e escolha uma das seções da planta.",
        "Use <strong>Aumentar zoom</strong>, <strong>Diminuir zoom</strong> ou <strong>Redefinir zoom</strong> quando necessário.",
        "Selecione uma sala identificada para abrir o mesmo painel de controle.",
      ] },
      { t: "nota", texto: "Mover, redimensionar ou reorganizar a interface não altera esse fluxo: identifique sempre os nomes Cards, Lista, Planta baixa, bloco, andar e sala." },
    ],
  },
  {
    id: "estados-sala",
    titulo: "Entender os estados da sala",
    categoria: "salas",
    tags: ["online", "offline", "ligado", "desligado", "reservada", "visualização"],
    corpo: [
      { t: "tabela", cabecalho: ["Estado", "Como interpretar e agir"], linhas: [
        ["online · ligado", "o ESP32 está conectado e o estado informado é ligado"],
        ["online · desligado", "o ESP32 está conectado e o estado informado é desligado"],
        ["offline", "o servidor não recebe o controlador; consulte o painel antes de insistir em comandos"],
        ["reservada / agendamento ativo", "outro usuário pode bloquear seu controle até o horário indicado"],
        ["somente visualização", "a conta pode consultar, mas os comandos permanecem desabilitados"],
      ] },
      { t: "p", texto: "A conexão do website com o servidor e a conexão do ESP32 são estados diferentes. O site pode estar online enquanto uma sala está offline." },
      { t: "links", itens: [
        { id: "controlador", texto: "Operar o ar-condicionado" },
        { id: "conexao", texto: "Conexão e recuperação" },
      ] },
    ],
  },
  {
    id: "controlador",
    titulo: "Operar o ar-condicionado",
    categoria: "salas",
    tags: ["Power", "temperatura", "Cool", "Off", "Turbo", "controle"],
    verNoApp: "/salas",
    corpo: [
      { t: "p", texto: "O painel mostra temperatura ambiente, conexão, estado ligado/desligado, modo e temperatura-alvo. A implementação atual oferece <strong>Power</strong>, ajuste da temperatura-alvo e <strong>Turbo</strong>; não há seleção manual separada de modo, ventilação ou presets." },
      { t: "sub", titulo: "Ligar, desligar e ajustar" },
      { t: "passos", itens: [
        "Confirme a sala e os indicadores <strong>online/offline</strong>, <strong>ligado/desligado</strong> e eventual aviso de reserva.",
        "Use <strong>Power</strong> para alternar entre ligado e desligado. O modo exibido passa entre <strong>Cool</strong> e <strong>Off</strong>.",
        "Use <strong>Diminuir temperatura</strong> ou <strong>Aumentar temperatura</strong>; cada acionamento altera 1 °C e para nos limites efetivos da sala.",
        "Com o aparelho ligado, use <strong>Turbo</strong> para ativar ou desativar o reforço configurado pelo Superadministrador.",
        "Aguarde a atualização do painel. O novo alvo e o estado dos controles são a confirmação de aceite pelo servidor.",
      ] },
      { t: "fluxo", titulo: "Estado e ação", itens: [
        { tipo: "status", texto: "Permissão e reserva verificadas" },
        { tipo: "action", texto: "Power · temperatura · Turbo" },
        { tipo: "server", texto: "Servidor salva o estado desejado" },
        { tipo: "device", texto: "ESP32 aplica agora ou ao reconectar" },
        { tipo: "status", texto: "Painel recebe o estado atualizado" },
      ] },
      { t: "sub", titulo: "Quando um controle fica desabilitado" },
      { t: "lista", itens: [
        "<strong>Somente leitura</strong>: sua conta não possui controle para essa sala.",
        "<strong>Sala reservada por …</strong>: uma reserva ativa de outro usuário bloqueia usuários comuns até o fim indicado.",
        "<strong>Temperatura no limite</strong>: o botão correspondente fica desabilitado; isso é esperado.",
        "<strong>Turbo</strong>: só pode ser alterado com o aparelho ligado.",
      ] },
      { t: "nota", nivel: "atencao", texto: "Se o ESP32 estiver offline, o servidor pode aceitar e guardar o estado desejado. O painel avisa que ele será aplicado na reconexão; não interprete o aceite como confirmação física imediata." },
    ],
  },
  {
    id: "controle-acesso-sala",
    titulo: "Acesso a salas restritas e Config. de sala",
    categoria: "salas",
    tags: ["restrição", "proprietário", "conceder", "revogar", "somente leitura"],
    verNoApp: "/config",
    corpo: [
      { t: "p", texto: "Uma sala pode ser aberta para controle geral ou marcada como restrita. Em sala restrita, usuários comuns precisam de acesso explícito; admin mantém sua capacidade administrativa." },
      { t: "sub", titulo: "Para o proprietário de sala" },
      { t: "passos", itens: [
        "Abra <strong>Config.</strong> e selecione uma sala sob sua responsabilidade.",
        "Em <strong>Conceder acesso</strong>, escolha um usuário ativo e confirme.",
        "Confira a pessoa na lista de usuários com acesso.",
        "Para retirar a autorização, use <strong>revogar</strong> na pessoa desejada e confirme que ela saiu da lista.",
      ] },
      { t: "p", texto: "A lista de candidatos contém usuários comuns ativos. O proprietário administra apenas salas que lhe foram atribuídas; a ativação da restrição da sala é tarefa de Superadministrador." },
      { t: "nota", texto: "Conceder acesso não cria conta, não promove papel e não torna a pessoa proprietária. Se o controle continuar indisponível, verifique também a permissão geral de controle e uma possível reserva ativa." },
    ],
  },
]);
