ManualContent.registrar([
  {
    id: "conta-sessao",
    titulo: "Conta, sessão e sair",
    categoria: "conta",
    tags: ["menu", "inatividade", "logout", "expirar", "sessão"],
    corpo: [
      { t: "p", texto: "Abra o menu pelas iniciais da conta para conferir nome, login e papel, acessar <strong>Aplicativo móvel</strong> ou usar <strong>Sair</strong>." },
      { t: "lista", itens: [
        "A sessão expira depois do período de inatividade configurado. Antes disso, <strong>Sessão prestes a expirar</strong> oferece <strong>Continuar conectado</strong> ou <strong>Sair agora</strong>.",
        "Abas da mesma origem compartilham a sessão; sair ou ter a senha alterada encerra as demais.",
        "Fechar a tela sem usar <strong>Sair</strong> pode manter a sessão válida até a expiração. Em dispositivo compartilhado, sempre saia explicitamente.",
        "A URL conserva apenas a rota permitida e nunca deve conter a credencial.",
      ] },
      { t: "nota", texto: "A conta inicial Superadministrador pode exibir um alerta de senha padrão. Somente esse usuário recebe o fluxo de troca correspondente; após a alteração, as sessões são encerradas." },
    ],
  },
  {
    id: "conexao",
    titulo: "Conexão, modo offline e manutenção",
    categoria: "conta",
    tags: ["sem conexão", "reconectar", "offline", "servidor", "manutenção"],
    corpo: [
      { t: "tabela", cabecalho: ["Mensagem ou estado", "O que significa"], linhas: [
        ["Sem conexão com o servidor", "o website não alcança a API; a reconexão é automática"],
        ["Sala offline", "somente o controlador daquela sala não está conectado"],
        ["Sistema em manutenção", "o acesso de usuário comum está temporariamente bloqueado"],
        ["Conectar este aplicativo", "o Cordova ainda não conhece a origem do servidor"],
      ] },
      { t: "sub", titulo: "Recuperação" },
      { t: "passos", itens: [
        "Confira a rede do aparelho e se outras páginas internas abrem.",
        "Aguarde a reconexão automática; evite repetir comandos cujo aceite já apareceu.",
        "No app Android configurável, confirme a origem completa do servidor e se ela é alcançável pela mesma rede.",
        "Se somente uma sala estiver offline, relate a sala e o horário; administradores podem consultar <strong>Administração &gt; Dispositivos &gt; Histórico</strong>.",
      ] },
      { t: "nota", nivel: "atencao", texto: "O shell da PWA pode abrir sem rede, mas login, estados, comandos, relatos e dados administrativos exigem o servidor." },
    ],
  },
  {
    id: "relatos",
    titulo: "Relatar e acompanhar um problema",
    categoria: "conta",
    tags: ["inseto", "erro", "suporte", "categoria", "resposta"],
    corpo: [
      { t: "p", texto: "Use <strong>Relatar problema</strong> em Início ou o botão com função de relatar problema presente na interface. O mesmo painel lista somente os relatos da conta atual." },
      { t: "passos", itens: [
        "Escolha a categoria adequada.",
        "Escreva um título objetivo (3 a 140 caracteres) e uma descrição reproduzível (10 a 4.000 caracteres).",
        "Selecione a sala quando o problema estiver ligado a um ambiente específico.",
        "Envie e confira o relato na lista. Repetir o mesmo título e descrição em até 90 segundos não cria uma duplicata.",
        "Acompanhe <strong>novo</strong>, <strong>aberto</strong>, <strong>em análise</strong> ou <strong>resolvido</strong>; a resposta da equipe aparece no item correspondente.",
      ] },
      { t: "p", texto: "O sistema anexa contexto técnico limitado, como página, viewport, navegador e idioma, para facilitar o diagnóstico." },
      { t: "nota", nivel: "seguranca", texto: "Nunca informe senhas, tokens, segredos de ESP32, chaves de assinatura ou dados pessoais desnecessários." },
    ],
  },
  {
    id: "pwa-mobile",
    titulo: "Aplicativo, PWA e APK Android",
    categoria: "conta",
    tags: ["Aplicativo", "PWA", "APK", "Android", "instalar", "atualizar", "SHA-256"],
    verNoApp: "/aplicativo",
    corpo: [
      { t: "p", texto: "Abra <strong>Aplicativo</strong> no menu da conta ou em Início. A página distingue navegador, PWA e Cordova Android e mostra a publicação Android disponível quando o servidor possui um APK válido." },
      { t: "sub", titulo: "Instalar ou usar a PWA" },
      { t: "lista", itens: [
        "Em navegador compatível, use a ação de instalar ou adicionar à tela inicial. O procedimento exato pertence ao navegador.",
        "A PWA se atualiza sozinha quando é aberta com rede: baixa o shell novo, troca o cache e recarrega. Não é necessário limpar dados ou reinstalar.",
        "Sem rede ela abre a última interface armazenada, mas não executa operações dependentes do servidor.",
      ] },
      { t: "p", texto: "O cartão no topo da página resume a situação: <strong>Atualizado</strong>, <strong>Atualização disponível</strong> ou <strong>Versão instalada indisponível</strong>. Ele só compara versões dentro do aplicativo Android instalado; em navegador e na PWA a página mostra <strong>Versão disponível</strong>, porque ali não há como saber o que está instalado no aparelho. A verificação acontece ao abrir a página e ao voltar para ela, nunca de forma contínua, e nada é instalado sem a sua confirmação no Android." },
      { t: "sub", titulo: "Instalar ou atualizar o APK" },
      { t: "passos", itens: [
        "Na página <strong>Aplicativo</strong>, confira o cartão de situação no topo e a versão, a data e o tamanho publicados; build, SHA-256 e origem ficam em <strong>Detalhes técnicos</strong>.",
        "Use <strong>Baixar aplicativo</strong> — ou <strong>Baixar atualização</strong>, quando já houver uma instalação mais antiga. O website calcula e confere o SHA-256 antes de salvar; divergência cancela o arquivo.",
        "Abra o APK baixado e autorize a instalação por essa fonte apenas quando o Android solicitar.",
        "Confirme a substituição/atualização e reabra o RemoteIFES. Um build novo é necessário para instalar sobre a versão existente.",
      ] },
      { t: "fluxo", titulo: "Atualização Android", itens: [
        { tipo: "screen", texto: "Aplicativo" },
        { tipo: "status", texto: "Atualização disponível" },
        { tipo: "action", texto: "Baixar e verificar SHA-256" },
        { tipo: "device", texto: "Android confirma instalação" },
        { tipo: "status", texto: "Nova versão/build em uso" },
      ] },
      { t: "nota", texto: "O APK Cordova usa o mesmo frontend, mas pode vir com a origem do servidor fixa. Na variante configurável, a primeira execução mostra <strong>Conectar este aplicativo</strong>. Se o Android recusar a atualização, preserve os dados e procure uma publicação com build superior e a mesma assinatura." },
    ],
  },
  {
    id: "acessibilidade",
    titulo: "Acessibilidade e uso por teclado",
    categoria: "conta",
    tags: ["fonte", "dislexia", "contraste", "teclado", "Tab", "Enter", "Esc"],
    corpo: [
      { t: "p", texto: "Abra o controle identificado como <strong>Acessibilidade</strong>. Os ajustes valem para a interface inteira e ficam salvos neste aparelho." },
      { t: "lista", itens: [
        "Tamanho e tipo de fonte, incluindo dislexia, serifada e sem serifa.",
        "Espaçamento entre letras, altura de linha, largura de parágrafo e alinhamento.",
        "Contraste, cor do texto, destaque de links e ocultação de imagens.",
        "Cada grupo pode ser redefinido; <strong>Redefinir tudo</strong> restaura todos os padrões.",
        "Use Tab para percorrer controles, Enter ou Espaço para acionar e Esc para fechar painéis e o manual.",
      ] },
      { t: "nota", texto: "Ocultar imagens não remove nomes acessíveis nem muda a função. Se uma combinação reduzir a legibilidade, redefina o grupo afetado ou tudo." },
    ],
  },
  {
    id: "solucao-problemas",
    titulo: "Erros comuns e recuperação",
    categoria: "conta",
    tags: ["erro", "falha", "recuperar", "bloqueado", "antiga"],
    corpo: [
      { t: "tabela", cabecalho: ["Sintoma", "Verifique / faça"], linhas: [
        ["Login recusado", "tipo de acesso, credenciais e situação da conta"],
        ["Sessão encerrada", "entre novamente; inatividade, troca de senha ou administração pode tê-la fechado"],
        ["Site sem servidor", "rede e origem; aguarde a reconexão automática"],
        ["Uma sala offline", "não repita comandos já aceitos; informe sala e horário à equipe"],
        ["Controle desabilitado", "permissão geral, restrição da sala, reserva, limites e estado ligado para Turbo"],
        ["Comando aceito, sem efeito físico", "confira offline; o estado pode estar pendente para reconexão"],
        ["Tela antiga na PWA", "abra com rede e aguarde a atualização automática"],
        ["APK recusado", "build superior, mesma assinatura, origem publicável e permissão de instalação"],
        ["Manual sem tópico administrativo", "entre com o papel correto; conteúdo privilegiado vem do servidor"],
      ] },
      { t: "p", texto: "Ao relatar, registre a ação tentada, a mensagem exibida, a sala e o horário. Não envie segredos. Administradores podem correlacionar o evento em <strong>Administração &gt; Sistema &gt; Logs</strong> e <strong>Administração &gt; Dispositivos &gt; Histórico</strong>." },
      { t: "links", itens: [
        { id: "conexao", texto: "Conexão e modo offline" },
        { id: "relatos", texto: "Abrir um relato útil" },
      ] },
    ],
  },
]);
