const SALAS_CAMPUS = [
  { codigo: 'A-111', nome: 'CGP', bloco: 'A', andar: 1 },
  { codigo: 'A-110', nome: 'A-110', bloco: 'A', andar: 1 },
  { codigo: 'A-109', nome: 'CRA', bloco: 'A', andar: 1 },
  { codigo: 'A-108', nome: 'CTI', bloco: 'A', andar: 1 },
  { codigo: 'A-107', nome: 'LABORATÓRIO DE INFORMÁTICA II', bloco: 'A', andar: 1 },
  { codigo: 'A-106', nome: 'LABORATÓRIO DE INFORMÁTICA I', bloco: 'A', andar: 1 },
  { codigo: 'A-103b', nome: 'ENFERMARIA', bloco: 'A', andar: 1 },
  { codigo: 'A-103a', nome: 'CAM', bloco: 'A', andar: 1 },
  { codigo: 'A-105', nome: 'NAPNE', bloco: 'A', andar: 1 },
  { codigo: 'A-104', nome: 'CRA', bloco: 'A', andar: 1 },
  { codigo: 'A-209', nome: 'SALA DE MULTIMÍDIA', bloco: 'A', andar: 2 },
  { codigo: 'A-208', nome: 'A-208', bloco: 'A', andar: 2 },
  { codigo: 'A-207', nome: 'A-207', bloco: 'A', andar: 2 },
  { codigo: 'A-206', nome: 'A-206', bloco: 'A', andar: 2 },
  { codigo: 'A-205', nome: 'A-205', bloco: 'A', andar: 2 },
  { codigo: 'A-204', nome: 'A-204', bloco: 'A', andar: 2 },
  { codigo: 'A-202', nome: 'A-202', bloco: 'A', andar: 2 },
  { codigo: 'A-201a', nome: 'A-201a', bloco: 'A', andar: 2 },
  { codigo: 'A-203', nome: 'LABORATÓRIO DE INFORMÁTICA III', bloco: 'A', andar: 2 },
  { codigo: 'A-201d', nome: 'NAPNE', bloco: 'A', andar: 2 },
  { codigo: 'A-201c', nome: 'A-201c', bloco: 'A', andar: 2 },
  { codigo: 'A-201b', nome: 'TÁTICA JR.', bloco: 'A', andar: 2 },
  { codigo: 'A-210', nome: 'CAE', bloco: 'A', andar: 2 },
  { codigo: 'A-211', nome: 'A-211', bloco: 'A', andar: 2 },
  { codigo: 'A-313', nome: 'LABORATÓRIO DE QUÍMICA', bloco: 'A', andar: 3 },
  { codigo: 'A-312', nome: 'LABORATÓRIO DE FÍSICA', bloco: 'A', andar: 3 },
  { codigo: 'A-311', nome: 'LABORATÓRIO DE BIOLOGIA', bloco: 'A', andar: 3 },
  { codigo: 'A-310', nome: 'A-310', bloco: 'A', andar: 3 },
  { codigo: 'A-309', nome: 'A-309', bloco: 'A', andar: 3 },
  { codigo: 'A-306', nome: 'A-306', bloco: 'A', andar: 3 },
  { codigo: 'A-306b', nome: 'CLC, CEF, COC, CCO (DIAPL)', bloco: 'A', andar: 3 },
  { codigo: 'A-304', nome: 'DIREN COGE', bloco: 'A', andar: 3 },
  { codigo: 'A-302', nome: 'DG GABDG', bloco: 'A', andar: 3 },
  { codigo: 'A-314', nome: 'COOP', bloco: 'A', andar: 3 },
  { codigo: 'A-307', nome: 'LABORATÓRIO DE INFORMÁTICA CAD', bloco: 'A', andar: 3 },
  { codigo: 'A-305', nome: 'DIAPL', bloco: 'A', andar: 3 },
  { codigo: 'A-303', nome: 'DPPGE', bloco: 'A', andar: 3 },
  { codigo: 'A-301', nome: 'COORD. DE ADM.', bloco: 'A', andar: 3 },
  { codigo: 'B-113', nome: 'LABORATÓRIO DE FABRICAÇÃO', bloco: 'B', andar: 1 },
  { codigo: 'B-111', nome: 'LABORATÓRIO ENSAIOS DESTRUTIVOS', bloco: 'B', andar: 1 },
  { codigo: 'B-109', nome: 'LABORATÓRIO ENSAIO NÃO-DESTRUTIVOS', bloco: 'B', andar: 1 },
  { codigo: 'B-104', nome: 'LABORATÓRIO HIDRÁULICA', bloco: 'B', andar: 1 },
  { codigo: 'B-103', nome: 'LABORATÓRIO DE MÁQUINAS TÉRMICAS', bloco: 'B', andar: 1 },
  { codigo: 'B-102', nome: 'LABORATÓRIO MÁQUINAS TÉRMICAS E DE FLUXO', bloco: 'B', andar: 1 },
  { codigo: 'B-110', nome: 'LABORATÓRIO DE MECÂNICA', bloco: 'B', andar: 1 },
  { codigo: 'B-108-B-107', nome: 'LABORATÓRIO METROLOGIA', bloco: 'B', andar: 1 },
  { codigo: 'B-105-B-106', nome: 'LABORATÓRIO PREPARAÇÃO MOTOS', bloco: 'B', andar: 1 },
  { codigo: 'B-101', nome: 'ALMOXARIFADO E PATRIMÔNIO (CPMS) - (DIAPL)', bloco: 'B', andar: 1 },
  { codigo: 'B-112', nome: 'COORDENAÇÃO DO MECÂNICA', bloco: 'B', andar: 1 },
  { codigo: 'B-100', nome: 'APOIO', bloco: 'B', andar: 1 },
  { codigo: 'B-207', nome: 'LABORATÓRIO INSTALAÇÕES ELÉTRICAS', bloco: 'B', andar: 2 },
  { codigo: 'B-206', nome: 'SALA TÉCNICA', bloco: 'B', andar: 2 },
  { codigo: 'B-205', nome: 'LABORATÓRIO ELETRICIDADE E ELETRÔNICA', bloco: 'B', andar: 2 },
  { codigo: 'B-204', nome: 'LABORATÓRIO COMANDOS MÁQUINAS ELÉTRICAS', bloco: 'B', andar: 2 },
  { codigo: 'B-203', nome: 'LABORATÓRIO ELETRÔNICA DIGITAL', bloco: 'B', andar: 2 },
  { codigo: 'B-202', nome: 'LABORATÓRIO ELETRÔNICA DE POTÊNCIA', bloco: 'B', andar: 2 },
  { codigo: 'B-201', nome: 'LABORATÓRIO AUTOMAÇÃO', bloco: 'B', andar: 2 },
  { codigo: 'B-206b', nome: 'LAB. SOLDA', bloco: 'B', andar: 2 },
  { codigo: 'B-212', nome: 'EQUIP. TI', bloco: 'B', andar: 2 },
  { codigo: 'B2016', nome: 'SALA B16', bloco: 'B', andar: 2 },
  { codigo: 'B2014', nome: 'SALA B14', bloco: 'B', andar: 2 },
  { codigo: 'B2012', nome: 'SALA B12', bloco: 'B', andar: 2 },
  { codigo: 'B2010', nome: 'SALA B10', bloco: 'B', andar: 2 },
  { codigo: 'B208', nome: 'SALA B08', bloco: 'B', andar: 2 },
  { codigo: 'B206', nome: 'SALA B06', bloco: 'B', andar: 2 },
  { codigo: 'B204', nome: 'SALA B04', bloco: 'B', andar: 2 },
  { codigo: 'B202', nome: 'SALA B02', bloco: 'B', andar: 2 },
  { codigo: 'B2017', nome: 'SALA B17', bloco: 'B', andar: 2 },
  { codigo: 'B2015', nome: 'SALA B15', bloco: 'B', andar: 2 },
  { codigo: 'B2013', nome: 'SALA B13', bloco: 'B', andar: 2 },
  { codigo: 'B2011', nome: 'SALA B11', bloco: 'B', andar: 2 },
  { codigo: 'B200', nome: 'SALA B00', bloco: 'B', andar: 2 },
  { codigo: 'B207', nome: 'SALA B07', bloco: 'B', andar: 2 },
  { codigo: 'B205', nome: 'SALA B05', bloco: 'B', andar: 2 },
  { codigo: 'B203', nome: 'SALA B03', bloco: 'B', andar: 2 },
  { codigo: 'B201', nome: 'SALA B01', bloco: 'B', andar: 2 },
  { codigo: 'B-309', nome: 'LABORATÓRIO DE INTELIGÊNCIA ARTIFICIAL', bloco: 'B', andar: 3 },
  { codigo: 'B-307', nome: 'LABORATÓRIO DE PROJETOS APLICADOS', bloco: 'B', andar: 3 },
  { codigo: 'B-305', nome: 'LABORATÓRIO DE EXPERIMENTOS', bloco: 'B', andar: 3 },
  { codigo: 'B-302', nome: 'AUDITÓRIO', bloco: 'B', andar: 3 },
  { codigo: 'B-208', nome: 'SALA DE CONVIVÊNCIA DOS SERVIDORES', bloco: 'B', andar: 3 },
  { codigo: 'B-306', nome: 'LAB. ESTUDOS AVANÇADOS (LABSEA)', bloco: 'B', andar: 3 },
  { codigo: 'B-304', nome: 'LAB. DE REDES (AXOLAB)', bloco: 'B', andar: 3 },
  { codigo: 'B-303', nome: 'LAB. MÁQUINAS ELÉTRICAS', bloco: 'B', andar: 3 },
  { codigo: 'B-301', nome: 'LAB. FONTES RENOVÁVEIS E SISTEMAS DE ENERGIA', bloco: 'B', andar: 3 },
  { codigo: 'B-300', nome: 'BIBLIOTECA', bloco: 'B', andar: 3 },
];

module.exports = SALAS_CAMPUS;