const adminSections = [
  {
    id: "administracao",
    titulo: "Visão geral de Administração",
    papel: "admin",
    categoria: "admin_operacao",
    tags: ["Admin", "permissões", "limites"],
    verNoApp: "/admin/usuarios",
    corpo: [
      { t: "p", texto: "A seção <strong>Admin</strong> reúne a operação administrativa em quatro grupos — <strong>Gestão</strong>, <strong>Dispositivos</strong>, <strong>Monitoramento</strong> e <strong>Sistema</strong> —, sempre em dois níveis: <strong>Administração &gt; Grupo &gt; Função</strong>. O admin herda o uso comum e enxerga apenas as funções que seu nível autoriza; funções de infraestrutura permanecem exclusivas do Superadministrador e nem sequer aparecem no grupo." },
      { t: "tabela", cabecalho: ["Grupo", "Funções e uso principal"], linhas: [
        ["Gestão", "Usuários, Proprietários de sala e (Superadministrador) Relatos de problemas: a operação administrativa de rotina"],
        ["Dispositivos", "Cadastro, Histórico, Notificações e Firmware / OTA: o ciclo de vida dos ESP32"],
        ["Monitoramento", "Ativos, Mapa e (Superadministrador) Saúde do sistema: observação de estado e diagnóstico"],
        ["Sistema", "Sessões, Logs, Acessos ESP32 e (Superadministrador) Configurações e Auditoria: configuração, segurança e trilhas de histórico"],
      ] },
      { t: "fluxo", titulo: "Grupo Dispositivos", itens: [
        { tipo: "screen", texto: "Cadastro: vincular o ESP32 à sala" },
        { tipo: "status", texto: "Histórico: conexões e quedas do dispositivo" },
        { tipo: "status", texto: "Notificações: avisos compartilhados" },
        { tipo: "device", texto: "Firmware / OTA: atualizar e manter a placa" },
      ] },
      { t: "nota", texto: "Configurações globais, restrição da sala, Cadastro de ESP32, credenciais, IR, Firmware / OTA, Saúde do sistema, Auditoria e gestão de relatos exigem Superadministrador, mesmo que uma URL ou um atalho antigo tente abri-los." },
    ],
  },
  {
    id: "agenda-grade",
    titulo: "Agenda e Grade",
    papel: "admin",
    categoria: "admin_operacao",
    tags: ["Agendamentos", "reserva", "conflito", "horário", "Grade"],
    verNoApp: "/agenda",
    corpo: [
      { t: "p", texto: "<strong>Agenda</strong> cria reservas do dia atual no fuso de Brasília. <strong>Grade</strong> consulta, por sala e data, os períodos fixos entre 07:00 e 22:10. Na implementação atual não existe edição: para corrigir dados, exclua e recrie." },
      { t: "fluxo", titulo: "Novo agendamento", itens: [
        { tipo: "screen", texto: "Agenda" },
        { tipo: "action", texto: "Sala" },
        { tipo: "action", texto: "Início e fim" },
        { tipo: "decision", texto: "Reserva · ligar período inteiro · ligar em intervalo" },
        { tipo: "action", texto: "Temperatura e Salvar" },
        { tipo: "status", texto: "Item aparece na lista e na Grade" },
      ] },
      { t: "passos", itens: [
        "Antes de criar, abra <strong>Grade</strong>, escolha sala e data e confira os períodos ocupados.",
        "Em <strong>Agenda</strong>, escolha a sala. A data é o dia atual e não é editável.",
        "Informe horários válidos no formato mostrado, com início anterior ao fim, e uma temperatura dentro dos limites efetivos da sala.",
        "Escolha o comportamento: apenas reservar; ligar durante todo o período; ou ligar somente em um intervalo contido na reserva.",
        "Use <strong>Salvar</strong>. O sucesso é o novo item na lista; a Grade passa a representar reserva e acionamento nos períodos correspondentes.",
      ] },
      { t: "sub", titulo: "Manter e corrigir" },
      { t: "lista", itens: [
        "Use o controle de ativo para suspender ou reativar um agendamento sem apagá-lo.",
        "Use <strong>remover</strong> no agendamento desejado para remoção definitiva; recrie se precisar alterar sala, horário, temperatura ou modo.",
        "Sobreposição com outro agendamento ativo na mesma sala e data é recusada.",
        "Também são recusados horário invertido, intervalo de acionamento fora da reserva, temperatura fora dos limites, sala/data inválida e excesso do limite administrativo.",
      ] },
      { t: "nota", nivel: "atencao", texto: "A reserva ativa bloqueia o controle manual de outros usuários comuns. Admin pode intervir, portanto confira sala e horário antes de salvar ou excluir." },
      { t: "links", itens: [{ id: "estados-sala", texto: "Estados e reserva no painel" }, { id: "logs-dispositivos", texto: "Confirmar execuções nos históricos" }] },
    ],
  },
  {
    id: "usuarios-admin",
    titulo: "Usuários: criar, alterar e desativar",
    papel: "admin",
    categoria: "admin_operacao",
    tags: ["Usuários", "senha", "desativar", "reativar", "excluir", "promover"],
    verNoApp: "/admin/usuarios",
    corpo: [
      { t: "sub", titulo: "Criar conta" },
      { t: "passos", itens: [
        "Abra <strong>Administração &gt; Gestão &gt; Usuários</strong> e use a ação de nova conta.",
        "Informe login (letras, números, ponto, sublinhado, hífen ou @; sem espaços; até 60 caracteres), nome (até 120) e senha de 8 a 128 caracteres.",
        "Defina se a conta <strong>pode controlar</strong>. Admin comum cria somente usuário comum; apenas Superadministrador pode conceder papel administrativo.",
        "Salve e confirme a nova conta na lista. Entregue a senha por um canal apropriado e solicite troca conforme a política local.",
      ] },
      { t: "sub", titulo: "Manutenção da conta" },
      { t: "lista", itens: [
        "Nome, login, senha e permissão de controle podem ser atualizados dentro dos limites do papel atual.",
        "Trocar a senha encerra todas as sessões daquela conta.",
        "<strong>Desativar</strong> impede novos usos; <strong>Reativar</strong> devolve o acesso. Prefira desativar quando houver chance de retorno.",
        "<strong>Excluir</strong> é permanente e remove vínculos operacionais como agendamentos, execuções, propriedade, acessos e sessões. O relato preserva um retrato do autor.",
        "Somente Superadministrador promove, rebaixa ou altera outra conta administrativa. A conta Superadministrador inicial não pode ser removida nem rebaixada.",
      ] },
      { t: "nota", nivel: "atencao", texto: "Antes de desativar ou excluir, transfira responsabilidades de proprietário e avalie agendamentos. Confirme o login e o nome; ações destrutivas não têm desfazer na interface." },
    ],
  },
  {
    id: "proprietarios-admin",
    titulo: "Proprietários, acessos e Mapa",
    papel: "admin",
    categoria: "admin_operacao",
    tags: ["Proprietários de sala", "Mapa", "acesso", "delegar"],
    verNoApp: "/admin/proprietarios",
    corpo: [
      { t: "p", texto: "Em <strong>Administração &gt; Gestão &gt; Proprietários de sala</strong>, associe usuários comuns ativos às salas que eles poderão administrar pela aba <strong>Config.</strong>. A delegação permite conceder e revogar acesso, mas não permite ativar a própria restrição." },
      { t: "passos", itens: [
        "Selecione a sala e o usuário comum.",
        "Conceda a propriedade e confirme o vínculo listado.",
        "Oriente o proprietário a abrir <strong>Config.</strong> e administrar os usuários daquela sala.",
        "Revogue a propriedade quando a responsabilidade terminar; revise separadamente os acessos que já tenham sido concedidos.",
      ] },
      { t: "p", texto: "<strong>Administração &gt; Monitoramento &gt; Mapa</strong> consolida conexão, ligado/desligado e reservas por sala. É uma visão de triagem: selecione a sala ou use as funções específicas para investigar; o mapa não executa manutenção." },
      { t: "nota", texto: "A opção que torna a sala restrita é aplicada pelo servidor somente para Superadministrador. Admin comum pode manter proprietários e listas permitidas, mas não mudar esse estado." },
      { t: "links", itens: [{ id: "controle-acesso-sala", texto: "Procedimento do proprietário" }, { id: "esp32-cadastro", texto: "Cadastro, restrição e limites por sala (Superadmin)" }] },
    ],
  },
  {
    id: "ativos-sessoes",
    titulo: "Ativos e Sessões",
    papel: "admin",
    categoria: "admin_historicos",
    tags: ["online", "inativo", "login", "logout", "histórico"],
    verNoApp: "/admin/ativos",
    corpo: [
      { t: "p", texto: "<strong>Administração &gt; Monitoramento &gt; Ativos</strong> mostra presença recente: online, inativo ou offline conforme sessão e limiar configurado. Use-o para operação corrente, não como registro definitivo de frequência." },
      { t: "p", texto: "<strong>Administração &gt; Sistema &gt; Sessões</strong> mantém login, logout e duração. Filtre pela data quando investigar acesso. Reiniciar o servidor fecha sessões que estavam abertas; expiração, saída e troca de senha também alteram o histórico." },
      { t: "sub", titulo: "Excluir histórico" },
      { t: "lista", itens: [
        "<strong>Excluir data</strong> remove os registros do dia filtrado; <strong>Excluir tudo</strong> remove todo o histórico da aba.",
        "A confirmação é deliberada e a exclusão é irreversível. Preserve fora do sistema o que for exigido por auditoria antes de apagar.",
        "Apagar histórico não exclui usuários e não encerra uma sessão atual por si só.",
      ] },
    ],
  },
  {
    id: "logs-dispositivos",
    titulo: "Logs, Histórico de dispositivos e Acessos ESP32",
    papel: "admin",
    categoria: "admin_historicos",
    tags: ["Logs", "Histórico", "Dispositivos", "Acessos ESP32", "comando", "origem"],
    verNoApp: "/admin/logs",
    corpo: [
      { t: "tabela", cabecalho: ["Função", "Evidência disponível"], linhas: [
        ["Sistema > Logs", "comando, valor, sala, usuário/sistema, origem e horário; até 300 resultados por consulta"],
        ["Dispositivos > Histórico", "eventos de conexão dos controladores, filtráveis por data"],
        ["Sistema > Acessos ESP32", "acessos registrados pelos controladores à interface/serviço local, filtráveis por data"],
      ] },
      { t: "passos", itens: [
        "Comece pela sala e pelo intervalo relatados.",
        "Em <strong>Administração &gt; Sistema &gt; Logs</strong>, filtre data, sala ou andar e compare a origem: manual, agendamento ou sistema.",
        "Em <strong>Administração &gt; Dispositivos &gt; Histórico</strong>, confirme quedas e retornos próximos ao comando.",
        "Use <strong>Administração &gt; Sistema &gt; Acessos ESP32</strong> como evidência complementar, não como confirmação de que o ar respondeu ao infravermelho.",
      ] },
      { t: "nota", nivel: "atencao", texto: "Logs e Acessos ESP32 permitem excluir a data filtrada ou tudo, com confirmação e sem recuperação. O Histórico de dispositivos é somente consulta. Nenhuma dessas funções mede o efeito físico no aparelho." },
    ],
  },
  {
    id: "notificacoes",
    titulo: "Notificações de dispositivos",
    papel: "admin",
    categoria: "admin_historicos",
    tags: ["sino", "lidas", "offline", "OTA", "monitoramento"],
    verNoApp: "/admin/notificacoes",
    corpo: [
      { t: "p", texto: "O sino e <strong>Administração &gt; Dispositivos &gt; Notificações</strong> exibem a mesma fila global. O servidor cria avisos de dispositivo offline, resultado de OTA e alertas de monitoramento; não existe criação manual." },
      { t: "lista", itens: [
        "Selecione uma notificação não lida para marcá-la como lida nos dois lugares.",
        "<strong>Marcar todas como lidas</strong> zera o indicador para a fila compartilhada, portanto afeta o que todos os administradores verão como pendente.",
        "Ler não resolve a causa. Abra <strong>Dispositivos &gt; Histórico</strong>, <strong>Monitoramento &gt; Saúde do sistema</strong> ou <strong>Dispositivos &gt; Firmware / OTA</strong> conforme o tipo e registre a intervenção quando necessário.",
      ] },
    ],
  },
];

module.exports = adminSections;
