const adminSections = [
  {
    id: "administracao",
    titulo: "Visão geral de Administração",
    papel: "admin",
    categoria: "admin_operacao",
    tags: ["Admin", "permissões", "limites"],
    verNoApp: "/admin/usuarios",
    corpo: [
      { t: "p", texto: "A seção <strong>Admin</strong> reúne a operação administrativa em três grupos — <strong>Gestão</strong>, <strong>Dispositivos</strong> e <strong>Sistema</strong> —, sempre em dois níveis: <strong>Administração &gt; Grupo &gt; Função</strong>. O admin herda o uso comum e enxerga apenas as funções que seu nível autoriza; funções de infraestrutura permanecem exclusivas do Superadministrador e nem sequer aparecem no grupo." },
      { t: "tabela", cabecalho: ["Grupo", "Conceito", "Funções"], linhas: [
        ["Gestão", "contas e responsabilidade sobre salas", "Usuários e (Superadministrador) Relatos de problemas"],
        ["Dispositivos", "administração dos ESP32 e avisos operacionais", "Alertas e (Superadministrador) Cadastro, Firmware / OTA e Protocolos IR"],
        ["Sistema", "informação corrente, histórico e configuração", "Logs, Status e (Superadministrador) Configurações"],
      ] },
      { t: "p", texto: "Dentro de <strong>Sistema</strong>, a divisão é temporal: <strong>Status</strong> guarda o que está acontecendo agora e <strong>Logs</strong> guarda o que já aconteceu e ficou persistido. <strong>Configurações</strong> é a configuração do sistema." },
      { t: "sub", titulo: "Abas internas" },
      { t: "tabela", cabecalho: ["Função", "Abas internas"], linhas: [
        ["Gestão > Usuários", "Contas · Proprietários de sala"],
        ["Sistema > Logs", "Comandos · Acessos · Dispositivos · Sessões · Auditoria"],
        ["Sistema > Status", "Usuários ativos · Mapa · Sistema"],
      ] },
      { t: "fluxo", titulo: "Grupo Dispositivos", itens: [
        { tipo: "screen", texto: "Cadastro: vincular o ESP32 à sala (Superadministrador)" },
        { tipo: "device", texto: "Firmware / OTA: atualizar e manter a placa (Superadministrador)" },
        { tipo: "action", texto: "Protocolos IR: clonar e aplicar sinais (Superadministrador)" },
        { tipo: "status", texto: "Alertas: avisos compartilhados da fila do sino (todo admin)" },
      ] },
      { t: "nota", texto: "A permissão vale por aba interna, não pela tela que a contém: <strong>Status</strong> abre para qualquer admin por causa de Usuários ativos e Mapa, mas a aba <strong>Sistema</strong> continua exclusiva do Superadministrador; o mesmo vale para <strong>Auditoria</strong> dentro de Logs. Configurações globais, restrição da sala, Cadastro de ESP32, credenciais, Protocolos IR, Firmware / OTA, Status &gt; Sistema, Logs &gt; Auditoria e gestão de relatos exigem Superadministrador, mesmo que uma URL ou um atalho antigo tente abri-los." },
    ],
  },
  {
    id: "agenda-grade",
    titulo: "Agenda e Grade",
    papel: "admin",
    categoria: "admin_operacao",
    tags: ["Agendamentos", "reserva", "conflito", "horário", "Grade"],
    verNoApp: "/agenda",
    corpo: [
      { t: "p", texto: "<strong>Agenda</strong> cria reservas do dia atual no fuso de Brasília. <strong>Grade</strong> consulta, por sala e data, os períodos fixos entre 07:00 e 22:10. Na implementação atual não existe edição: para corrigir dados, exclua e recrie." },
      { t: "fluxo", titulo: "Novo agendamento", itens: [
        { tipo: "screen", texto: "Agenda" },
        { tipo: "action", texto: "Sala" },
        { tipo: "action", texto: "Início e fim" },
        { tipo: "decision", texto: "Reserva · ligar período inteiro · ligar em intervalo" },
        { tipo: "action", texto: "Temperatura e Criar agendamento" },
        { tipo: "status", texto: "Item aparece na lista e na Grade" },
      ] },
      { t: "passos", itens: [
        "Antes de criar, abra <strong>Grade</strong>, escolha sala e data e confira os períodos ocupados.",
        "Em <strong>Agenda</strong>, escolha a sala. A data é o dia atual e não é editável.",
        "Informe horários válidos no formato mostrado, com início anterior ao fim, e uma temperatura dentro dos limites efetivos da sala.",
        "Escolha o comportamento: apenas reservar; ligar durante todo o período; ou ligar somente em um intervalo contido na reserva.",
        "Use <strong>Criar agendamento</strong>. O sucesso é o novo item na lista; a Grade passa a representar reserva e acionamento nos períodos correspondentes.",
      ] },
      { t: "sub", titulo: "Manter e corrigir" },
      { t: "lista", itens: [
        "Use o controle de ativo para suspender ou reativar um agendamento sem apagá-lo. A reativação é recusada se houver conflito com outra reserva ativa na mesma sala e data.",
        "Use <strong>remover</strong> no agendamento desejado para remoção definitiva; recrie se precisar alterar sala, horário, temperatura ou modo.",
        "O período vale do início até o minuto anterior ao fim. Criado ou reativado com o intervalo de ligar em andamento, o agendamento liga o ar na próxima verificação (até 1 min) e desliga no fim; criado só depois de esse intervalo terminar, ele não liga nem desliga nada — a reserva, se ainda vigente, continua bloqueando a sala.",
        "Desativar ou remover um agendamento em curso libera a reserva e cancela o desligamento previsto para o fim; o ar-condicionado que ele já ligou continua ligado até um comando manual ou outro agendamento. Um ajuste manual do autor (ou de um admin) dentro do período não cancela o desligamento do fim.",
        "Sobreposição com outro agendamento ativo na mesma sala e data é recusada.",
        "Também são recusados horário invertido, intervalo de acionamento fora da reserva, temperatura fora dos limites, sala/data inválida e excesso do limite administrativo.",
      ] },
      { t: "nota", nivel: "atencao", texto: "A reserva ativa bloqueia o controle manual de outros usuários comuns. Admin pode intervir, portanto confira sala e horário antes de salvar ou excluir." },
      { t: "links", itens: [{ id: "estados-sala", texto: "Estados e reserva no painel" }, { id: "logs-dispositivos", texto: "Confirmar execuções nos históricos" }] },
    ],
  },
  {
    id: "usuarios-admin",
    titulo: "Usuários: criar, alterar e desativar",
    papel: "admin",
    categoria: "admin_operacao",
    tags: ["Usuários", "senha", "desativar", "reativar", "excluir", "promover"],
    verNoApp: "/admin/usuarios",
    corpo: [
      { t: "sub", titulo: "Criar conta" },
      { t: "passos", itens: [
        "Abra <strong>Administração &gt; Gestão &gt; Usuários &gt; Contas</strong> e use a ação de nova conta.",
        "Informe login (letras, números, ponto, sublinhado, hífen ou @; sem espaços; até 60 caracteres), nome (até 120) e senha de 8 a 128 caracteres.",
        "Defina se a conta <strong>pode controlar</strong>. Admin comum cria somente usuário comum; apenas Superadministrador pode conceder papel administrativo.",
        "Salve e confirme a nova conta na lista. Entregue a senha por um canal apropriado e solicite troca conforme a política local.",
      ] },
      { t: "sub", titulo: "Manutenção da conta" },
      { t: "lista", itens: [
        "Nome, login, senha e permissão de controle podem ser atualizados dentro dos limites do papel atual.",
        "Trocar a senha encerra todas as sessões daquela conta.",
        "<strong>Desativar</strong> impede novos usos; <strong>Reativar</strong> devolve o acesso. Prefira desativar quando houver chance de retorno.",
        "<strong>Excluir</strong> é permanente e remove vínculos operacionais como agendamentos, execuções, propriedade, acessos e sessões. O relato preserva um retrato do autor.",
        "Somente Superadministrador promove, rebaixa ou altera outra conta administrativa. A conta Superadministrador inicial não pode ser removida nem rebaixada.",
      ] },
      { t: "nota", nivel: "atencao", texto: "Antes de desativar ou excluir, transfira responsabilidades de proprietário e avalie agendamentos. Confirme o login e o nome; ações destrutivas não têm desfazer na interface." },
    ],
  },
  {
    id: "proprietarios-admin",
    titulo: "Proprietários de sala e acessos",
    papel: "admin",
    categoria: "admin_operacao",
    tags: ["Proprietários de sala", "acesso", "delegar"],
    verNoApp: "/admin/usuarios/proprietarios",
    corpo: [
      { t: "p", texto: "Em <strong>Administração &gt; Gestão &gt; Usuários &gt; Proprietários de sala</strong>, associe usuários comuns ativos às salas que eles poderão administrar pela aba <strong>Config.</strong>. A delegação permite conceder e revogar acesso, mas não permite ativar a própria restrição." },
      { t: "passos", itens: [
        "Selecione a sala e o usuário comum.",
        "Conceda a propriedade e confirme o vínculo listado.",
        "Oriente o proprietário a abrir <strong>Config.</strong> e administrar os usuários daquela sala.",
        "Revogue a propriedade quando a responsabilidade terminar; revise separadamente os acessos que já tenham sido concedidos.",
      ] },
      { t: "nota", texto: "A opção que torna a sala restrita é aplicada pelo servidor somente para Superadministrador. Admin comum pode manter proprietários e listas permitidas, mas não mudar esse estado." },
      { t: "links", itens: [{ id: "controle-acesso-sala", texto: "Procedimento do proprietário" }, { id: "status-mapa", texto: "Mapa de status das salas" }, { id: "esp32-cadastro", texto: "Cadastro, restrição e limites por sala (Superadmin)" }] },
    ],
  },
  {
    id: "status-mapa",
    titulo: "Status > Mapa: visão geral das salas",
    papel: "admin",
    categoria: "admin_historicos",
    tags: ["Mapa", "status", "triagem", "online", "reserva"],
    verNoApp: "/admin/status/mapa",
    corpo: [
      { t: "p", texto: "<strong>Administração &gt; Sistema &gt; Status &gt; Mapa</strong> consolida, por sala, a presença do ESP32 (online/offline), o estado desejado (ligado/desligado) e a reserva em vigor. É uma visão de triagem do momento: selecione a sala ou use as funções específicas para investigar; o mapa não executa manutenção nem comandos." },
      { t: "nota", nivel: "atencao", texto: "<em>Online</em> é presença (a placa foi vista há pouco), não prova de que o ar-condicionado está funcionando: o estado exibido é o desejado no servidor; a confirmação da placa aparece no painel da sala e em <strong>Dispositivos &gt; Firmware / OTA</strong>, e o efeito físico só se confere no aparelho." },
      { t: "links", itens: [{ id: "estados-sala", texto: "Estados e reserva no painel" }, { id: "logs-dispositivos", texto: "Históricos persistidos" }] },
    ],
  },
  {
    id: "ativos-sessoes",
    titulo: "Status > Usuários ativos",
    papel: "admin",
    categoria: "admin_historicos",
    tags: ["online", "inativo", "presença", "sessão"],
    verNoApp: "/admin/status/ativos",
    corpo: [
      { t: "p", texto: "<strong>Administração &gt; Sistema &gt; Status &gt; Usuários ativos</strong> mostra presença recente: online, inativo ou offline conforme sessão e limiar configurado. Use-o para operação corrente, não como registro definitivo de frequência; a aba é só leitura." },
      { t: "links", itens: [{ id: "sessoes-historico", texto: "Histórico de login e logout (Logs > Sessões)" }] },
    ],
  },
  {
    id: "sessoes-historico",
    titulo: "Logs > Sessões: histórico de login e logout",
    papel: "admin",
    categoria: "admin_historicos",
    tags: ["login", "logout", "histórico", "sessões", "excluir"],
    verNoApp: "/admin/logs/sessoes",
    corpo: [
      { t: "p", texto: "<strong>Administração &gt; Sistema &gt; Logs &gt; Sessões</strong> mantém login, logout e duração de cada sessão. Filtre pela data (dia de Brasília) quando investigar acesso. Reiniciar o servidor fecha sessões que estavam abertas; expiração, saída e troca de senha também alteram o histórico." },
      { t: "sub", titulo: "Excluir histórico" },
      { t: "lista", itens: [
        "<strong>Excluir data</strong> remove os registros do dia filtrado; <strong>Excluir tudo</strong> remove todo o histórico da aba.",
        "A confirmação é deliberada e a exclusão é irreversível. Preserve fora do sistema o que for exigido por auditoria antes de apagar.",
        "Apagar histórico não exclui usuários e não encerra uma sessão atual por si só.",
      ] },
      { t: "links", itens: [{ id: "ativos-sessoes", texto: "Presença corrente (Status > Usuários ativos)" }, { id: "logs-dispositivos", texto: "Demais históricos" }] },
    ],
  },
  {
    id: "logs-dispositivos",
    titulo: "Logs: comandos, acessos e dispositivos",
    papel: "admin",
    categoria: "admin_historicos",
    tags: ["Logs", "Acessos", "Dispositivos", "Sessões", "comando", "origem", "histórico"],
    verNoApp: "/admin/logs",
    corpo: [
      { t: "p", texto: "<strong>Administração &gt; Sistema &gt; Logs</strong> reúne a informação já persistida. Cada aba interna guarda um histórico próprio, com filtros e política de retenção independentes; o que está acontecendo agora fica em <strong>Sistema &gt; Status</strong>." },
      { t: "tabela", cabecalho: ["Aba interna", "Evidência disponível"], linhas: [
        ["Comandos", "comando, valor, sala, quem pediu (a conta, ou “sistema” quando não houve conta), origem (manual, agendamento ou esp32_local) e horário; até 300 resultados por consulta"],
        ["Acessos", "requisições registradas pelos controladores ao servidor, com IP de origem e filtro por data"],
        ["Dispositivos", "eventos de conexão e desconexão dos controladores, filtráveis por data"],
        ["Sessões", "login, logout e duração por usuário, filtráveis por data"],
        ["Auditoria (Superadministrador)", "eventos administrativos e períodos de indisponibilidade dos ESP32"],
      ] },
      { t: "passos", itens: [
        "Comece pela sala e pelo intervalo relatados.",
        "Na aba <strong>Comandos</strong>, filtre data, sala ou andar e compare a origem: <code>manual</code> (uma conta), <code>agendamento</code> (o agendador, mostrado como “sistema” na coluna do usuário) ou <code>esp32_local</code> (registrado pela própria placa, como o failsafe OFF do switch).",
        "Na aba <strong>Dispositivos</strong>, confirme quedas e retornos próximos ao comando.",
        "A aba <strong>Acessos</strong> reúne as requisições dos controladores ao servidor: use-a como evidência complementar, não como confirmação de que o ar respondeu ao infravermelho.",
      ] },
      { t: "nota", nivel: "atencao", texto: "As abas <strong>Comandos</strong>, <strong>Acessos</strong> e <strong>Sessões</strong> permitem excluir a data filtrada ou tudo, com confirmação e sem recuperação. <strong>Dispositivos</strong> é somente consulta e <strong>Auditoria</strong> expira sozinha pela retenção. Nenhuma dessas funções mede o efeito físico no aparelho." },
    ],
  },
  {
    id: "notificacoes",
    titulo: "Notificações do sistema",
    papel: "admin",
    categoria: "admin_historicos",
    tags: ["sino", "lidas", "offline", "OTA", "monitoramento"],
    verNoApp: "/admin/notificacoes",
    corpo: [
      { t: "p", texto: "O sino e <strong>Administração &gt; Dispositivos &gt; Alertas</strong> exibem a mesma fila global. O servidor cria avisos de dispositivo offline, resultado de OTA e alertas de monitoramento; não existe criação manual." },
      { t: "lista", itens: [
        "Selecione uma notificação não lida para marcá-la como lida nos dois lugares.",
        "<strong>Marcar todas como lidas</strong> zera o indicador para a fila compartilhada, portanto afeta o que todos os administradores verão como pendente.",
        "Ler não resolve a causa. Abra <strong>Sistema &gt; Logs &gt; Dispositivos</strong>, <strong>Sistema &gt; Status &gt; Sistema</strong> ou <strong>Dispositivos &gt; Firmware / OTA</strong> conforme o tipo e registre a intervenção quando necessário.",
      ] },
    ],
  },
];

module.exports = adminSections;
