const C = require("./commands");

module.exports = [
  {
    id: "esp32-cadastro",
    titulo: "Cadastro: detectar e vincular ESP32 às salas",
    papel: "superadmin",
    categoria: "super_dispositivos",
    tags: ["Cadastro", "MAC", "detectado", "vincular", "limites", "restrição"],
    verNoApp: "/admin/macs",
    corpo: [
      { t: "p", texto: "<strong>Administração &gt; Dispositivos &gt; Cadastro</strong> é a fonte operacional para associar uma placa a uma sala. A área separa dispositivos detectados ainda sem vínculo e as salas da planta. É a primeira função do grupo <strong>Dispositivos</strong>, que segue com <strong>Firmware / OTA</strong>, <strong>Protocolos IR</strong> e <strong>Alertas</strong>." },
      { t: "sub", titulo: "Vincular um dispositivo detectado" },
      { t: "passos", itens: [
        "Ligue o ESP32 já configurado para alcançar o servidor e aguarde aparecer em <strong>ESP32 detectados na rede</strong> com MAC, IP, sala informada e último contato.",
        "Confirme fisicamente qual placa e ambiente estão sendo atendidos. Selecione a sala correta e use <strong>Vincular</strong>.",
        "Confira o MAC e o estado na sala. Assim que o servidor grava o vínculo, ele avisa em tempo real toda sessão administrativa aberta: o cadastro aparece sozinho, sem recarregar a página nem reabrir a aba, inclusive em uma segunda sessão autorizada. Se o salvamento falhar, nada passa a constar como cadastrado. O servidor rejeita MAC já associado a outra sala ou identificação incompatível.",
        "Use <strong>Descartar</strong> somente para remover uma detecção que não será aproveitada; a placa pode reaparecer se continuar se apresentando.",
      ] },
      { t: "sub", titulo: "Configuração por sala" },
      { t: "lista", itens: [
        "Edite ou limpe o MAC com cautela; sem associação o controlador não opera aquela sala.",
        "Limites mínimo e máximo em branco herdam os valores globais. Valores próprios precisam ficar entre 16 e 30 °C, com mínima menor que máxima; alvos e agendas fora do novo limite são ajustados.",
        "<strong>Acesso restrito</strong> exige autorização explícita de usuário comum. Prepare proprietários e acessos antes de ativar para evitar bloqueio inesperado.",
        "Trocar o MAC de uma sala que é a clonadora oficial invalida esse papel até o superadministrador confirmá-la novamente em <strong>Protocolos IR</strong>.",
      ] },
      { t: "nota", texto: "<strong>Cadastrado</strong> e <strong>conectado/online</strong> são estados independentes. O cartão da sala traz os dois selos: o de cadastro confirma que o servidor guardou o vínculo do MAC; o de conexão só fica online quando a placa realmente se apresenta. Um ESP32 recém-cadastrado costuma aparecer offline até estabelecer sua própria conexão, e isso não indica falha no cadastro." },
      { t: "nota", nivel: "atencao", texto: "Trocar MAC, limites ou restrição afeta a operação real. Registre a sala, preserve o vínculo anterior e valide status, controle e agendamento depois de salvar." },
      { t: "links", itens: [{ id: "esp32-setup-ap", texto: "Provisionar rede e servidor pelo setup AP" }, { id: "esp32-credenciais", texto: "Credencial exclusiva do dispositivo" }] },
    ],
  },
  {
    id: "esp32-setup-ap",
    titulo: "Setup AP e provisionamento",
    papel: "superadmin",
    categoria: "super_dispositivos",
    tags: ["RemoteIFES-Setup", "192.168.4.1", "Wi-Fi", "TLS", "provisionamento", "switch"],
    corpo: [
      { t: "p", texto: "A rede <strong>RemoteIFES-Setup</strong> só existe em três situações: quando a placa ainda não tem configuração válida de Wi-Fi e servidor, depois de <strong>Resetar Wi-Fi</strong> e por até dez minutos após um <strong>clique curto no switch físico</strong> (GPIO 26). Em operação normal o ponto de acesso e o portal local ficam desligados; o portal prepara Wi-Fi, servidor e, quando adotada, a credencial do ESP32, e é servido apenas pela interface desse ponto de acesso." },
      { t: "fluxo", titulo: "Provisionamento", itens: [
        { tipo: "device", texto: "ESP32 em setup AP" },
        { tipo: "action", texto: "Conectar a RemoteIFES-Setup" },
        { tipo: "screen", texto: "Abrir 192.168.4.1" },
        { tipo: "action", texto: "Wi-Fi · servidor · segurança · credencial" },
        { tipo: "device", texto: "Salvar e reiniciar" },
        { tipo: "server", texto: "Detectar, vincular o MAC em Dispositivos > Cadastro e validar" },
      ] },
      { t: "passos", itens: [
        "Em uma placa nova ou após Resetar Wi-Fi, o AP sobe sozinho. Em uma placa já em operação, dê um clique curto no switch físico: o AP abre por dez minutos sem derrubar a conexão com o servidor e fecha sozinho se nada for salvo.",
        "No equipamento de manutenção, conecte à rede <strong>RemoteIFES-Setup</strong> e abra <code>http://192.168.4.1</code>. Por padrão a rede é aberta; ela só pede a senha padrão do firmware (<strong>remoteifes</strong>) quando a opção global de exigir senha estiver ativada em Configurações.",
        "Informe SSID e senha da rede, host e porta do servidor. Escolha HTTPS com CA válida em produção; HTTPS sem validação ou HTTP são opções de desenvolvimento em rede controlada.",
        "Se usar credencial, informe <strong>deviceId</strong> e segredo juntos. Deixar ambos vazios preserva uma credencial já gravada.",
        "Salve. A placa reinicia, encerra o AP, conecta ao Wi-Fi e ao WebSocket do servidor. Confirme detecção, vínculo da sala, IP e versão em <strong>Administração &gt; Dispositivos &gt; Cadastro</strong>.",
      ] },
      { t: "nota", nivel: "seguranca", texto: "Enquanto o AP estiver aberto e sem senha, qualquer pessoa ao alcance do rádio alcança o portal e pode reprovisionar a placa. Onde o acesso físico não for controlado, ative <strong>Exigir senha na rede de configuração dos ESP32</strong> em Configurações. Essa opção é do Wi-Fi local e não substitui a credencial do dispositivo no servidor; nunca registre o segredo no manual, em relato ou em log." },
      { t: "p", texto: "Se falhar, use o monitor serial para distinguir autenticação Wi-Fi, DNS/host, porta, TLS e WebSocket. Sem configuração válida a placa permanece no AP; com configuração, o clique curto no switch reabre o portal a qualquer momento, independentemente da rede institucional." },
    ],
  },
  {
    id: "esp32-avancado",
    titulo: "ESP32: painel operacional, papéis e switch físico",
    papel: "superadmin",
    categoria: "super_dispositivos",
    tags: ["Firmware / OTA", "transmissor", "clonador", "failsafe", "switch", "GPIO 26", "buzzer", "Resetar Wi-Fi"],
    verNoApp: "/admin/esp32",
    corpo: [
      { t: "p", texto: "Em <strong>Administração &gt; Dispositivos &gt; Firmware / OTA</strong>, cada cartão distingue Wi-Fi/telemetria do servidor e conexão WebSocket ativa, além de versão, RSSI, temperatura, protocolo IR, failsafe OFF gravado na NVS, modo e último comando. É ali que ficam a credencial, a OTA e o reset de Wi-Fi de cada placa; a captura de sinais fica em <strong>Protocolos IR</strong>." },
      { t: "tabela", cabecalho: ["Papel", "Significado"], linhas: [
        ["Transmissor IR", "todo ESP32 de sala: emite comandos pelo LED IR (GPIO 4) e nunca captura sinais"],
        ["Clonador IR", "a única placa equipada com receptor IR (GPIO 15), definida pelo Superadministrador em Protocolos IR; também transmite"],
      ] },
      { t: "p", texto: "O papel é decidido pelo servidor e enviado à placa a cada conexão; o firmware não guarda essa escolha e ignora ordens de captura quando não é o clonador. O vínculo considera o MAC e a credencial atuais da sala: trocar a placa ou substituir a credencial exige confirmar a clonadora de novo." },
      { t: "sub", titulo: "Switch físico e buzzer" },
      { t: "p", texto: "Cada placa tem um único botão momentâneo entre o <strong>GPIO 26</strong> e o GND (pull-up interno, ativo em nível baixo, debounce de 40 ms) e um buzzer ativo no <strong>GPIO 27</strong> que soa brevemente a cada transmissão IR, sem atrasar o envio." },
      { t: "tabela", cabecalho: ["Ação no switch", "Efeito"], linhas: [
        ["Clique curto (solto antes de 5 s)", "abre o RemoteIFES-Setup por dez minutos sem derrubar a operação; um novo clique prorroga a janela"],
        ["Manter pressionado 5 s", "transmite uma única vez o failsafe OFF gravado na NVS, mesmo sem Wi-Fi ou servidor; soltar depois disso não abre o AP"],
      ] },
      { t: "nota", texto: "Sem failsafe gravado, a pressão de 5 s é reconhecida mas nada é transmitido. O failsafe é gravado ao aplicar, em Protocolos IR, um protocolo que tenha o comando OFF capturado; é apagado ao aplicar um protocolo sem failsafe, ao remover o failsafe do protocolo ou ao excluí-lo, e é ressincronizado sempre que a placa reconecta." },
      { t: "sub", titulo: "Resetar Wi-Fi" },
      { t: "nota", nivel: "atencao", texto: "<strong>Resetar Wi-Fi</strong> apaga rede e endereço do servidor da NVS e reinicia a placa no RemoteIFES-Setup. A credencial exclusiva e o failsafe OFF gravado são preservados. Tenha acesso físico e os dados corretos antes de confirmar." },
      { t: "links", itens: [{ id: "protocolos-ir", texto: "Clonar, guardar e aplicar protocolos IR" }, { id: "esp32-setup-ap", texto: "Provisionar pelo setup AP" }] },
    ],
  },
  {
    id: "protocolos-ir",
    titulo: "Protocolos IR: clonador oficial, biblioteca e failsafe OFF",
    papel: "superadmin",
    categoria: "super_dispositivos",
    tags: ["Protocolos IR", "clonador", "capturar", "label", "RAW", "failsafe OFF", "aplicar", "retransmitir"],
    verNoApp: "/admin/protocolos",
    corpo: [
      { t: "p", texto: "<strong>Administração &gt; Dispositivos &gt; Protocolos IR</strong> concentra o aprendizado de sinais: o Superadministrador define a clonadora oficial, entra no modo clone, dá um nome a cada captura e a guarda no servidor. Um protocolo salvo pode ser retransmitido por qualquer ESP32 conectado e, quando a biblioteca de infravermelho o reconhece, aplicado como protocolo operacional de uma sala." },
      { t: "fluxo", titulo: "Do controle remoto à sala", itens: [
        { tipo: "role", texto: "Definir a clonadora oficial" },
        { tipo: "action", texto: "Entrar no modo clone" },
        { tipo: "device", texto: "Receptor IR captura o sinal" },
        { tipo: "screen", texto: "Nomear e salvar na biblioteca" },
        { tipo: "server", texto: "Aplicar à sala e sincronizar o failsafe" },
      ] },
      { t: "passos", itens: [
        "Instale o receptor infravermelho somente na placa que fará a aprendizagem e escolha-a em <strong>Clonador oficial</strong>. O servidor passa a tratá-la como clonadora e todas as demais como transmissoras; capturas vindas de outra sala são recusadas.",
        "Com a clonadora conectada, use <strong>Entrar no modo clone</strong>. O receptor fica em captura contínua até o mesmo botão devolver a placa à operação; a placa recusa OTA enquanto estiver nesse modo.",
        "Aponte o controle original para o receptor e pressione o comando desejado. A leitura aparece em <strong>Última captura</strong>, com protocolo reconhecido ou sinal RAW genérico. Use <strong>testar</strong> para reenviá-la pela ESP32 de destino antes de salvar.",
        "Informe um nome com 2 a 80 caracteres, único na biblioteca sem diferenciar maiúsculas, e salve. Sinais RAW genéricos também podem ser guardados e testados, mas só protocolos reconhecidos viram protocolo operacional de sala.",
        "Na lista, escolha a ESP32 de destino para <strong>transmitir</strong> ou <strong>aplicar</strong>. Aplicar grava o protocolo na sala, envia o estado desejado e sincroniza o failsafe OFF do protocolo com a placa.",
        "Para o failsafe, use <strong>configurar failsafe OFF</strong> no protocolo e transmita ao receptor somente o botão de desligar do controle original. A próxima captura fica anexada ao protocolo; salas que já o usam recebem o RAW imediatamente ou ao reconectar.",
        "Ao terminar, use <strong>Sair do modo clone</strong>. Renomear e excluir também ficam na lista; excluir apaga o failsafe dos ESP32 que usavam o protocolo, sem alterar o protocolo operacional já gravado na sala.",
      ] },
      { t: "nota", nivel: "atencao", texto: "Só a clonadora oficial deve ter receptor IR. O modo clone é temporário: um sinal transmitido durante um teste pode acionar aparelhos próximos, então trabalhe com o equipamento alvo correto. Se o ESP32 da sala clonadora for trocado ou a credencial substituída, a tela avisa e é preciso confirmar a clonadora novamente." },
      { t: "links", itens: [{ id: "esp32-avancado", texto: "Switch físico, buzzer e failsafe local" }, { id: "esp32-cadastro", texto: "Cadastro e vínculo do MAC" }] },
    ],
  },
  {
    id: "ota-credenciais",
    titulo: "OTA e credenciais: visão geral segura",
    papel: "superadmin",
    categoria: "super_dispositivos",
    tags: ["OTA", "credencial", "firmware", "segredo"],
    verNoApp: "/admin/esp32",
    corpo: [
      { t: "p", texto: "A atualização OTA e a identidade por credencial são controles separados: OTA distribui uma imagem de firmware publicada; a credencial autentica a placa. Ambos são exclusivos do Superadministrador." },
      { t: "fluxo", titulo: "Relação entre as operações", itens: [
        { tipo: "server", texto: "Publicar firmware + SHA-256" },
        { tipo: "role", texto: "Superadministrador oferece OTA" },
        { tipo: "device", texto: "ESP32 autenticado baixa e valida" },
        { tipo: "status", texto: "Reinício: concluiu, falhou ou reverteu" },
      ] },
      { t: "links", titulo: "Procedimentos completos", itens: [{ id: "firmware-ota", texto: "Publicar e acompanhar OTA" }, { id: "esp32-credenciais", texto: "Provisionar, rotacionar, substituir ou revogar" }] },
    ],
  },
  {
    id: "esp32-credenciais",
    titulo: "Credenciais exclusivas de ESP32",
    papel: "superadmin",
    categoria: "super_dispositivos",
    tags: ["provisionar", "rotacionar", "substituir", "revogar", "deviceId"],
    verNoApp: "/admin/esp32",
    corpo: [
      { t: "tabela", cabecalho: ["Ação", "Efeito e uso"], linhas: [
        ["Provisionar", "cria deviceId e segredo; a sala passa a exigir a credencial, mesmo antes da exigência global"],
        ["Rotacionar", "mantém deviceId, cria segredo novo e aceita o anterior por 24 horas para transição"],
        ["Substituir", "cria nova identidade para outra placa, invalida e desconecta a antiga imediatamente"],
        ["Revogar", "invalida a identidade e encerra a conexão; exige novo provisionamento para voltar"],
      ] },
      { t: "p", texto: "Provisionar ou rotacionar envia o novo valor automaticamente a uma placa ainda conectada pelo vínculo atual. Substituir nunca envia a identidade nova à placa antiga: informe-a no setup da substituta. O servidor guarda somente o hash e mostra o segredo uma única vez." },
      { t: "p", texto: "Revogar mantém a exigência de credencial na sala, mesmo com a opção global desligada: o MAC sozinho não recupera o acesso. Para reconectar, provisione ou substitua a credencial e informe o novo valor no setup do dispositivo." },
      { t: "comando", titulo: "Gerenciar no host", comandos: C.credenciais, quando: "Quando a interface não estiver disponível ou a operação fizer parte de uma janela controlada.", preRequisitos: "Execute em remoteifes-server, com o mesmo .env e diretório de dados do serviço; troque A-101 pela sala real.", resultado: "O estado é exibido sem segredo; ações de criação mostram deviceId e segredo somente nessa execução.", risco: "Capture o segredo em canal seguro. Substituir ou revogar derruba a identidade anterior." },
      { t: "sub", titulo: "Migração de só MAC" },
      { t: "passos", itens: [
        "Mantenha <strong>Exigir credencial por dispositivo em todos os ESP32</strong> desligado.",
        "Provisione e valide cada sala; acompanhe <strong>Só MAC</strong> em <strong>Administração &gt; Sistema &gt; Status &gt; Sistema</strong>.",
        "Quando todas estiverem autenticadas, ative a exigência global e confirme que nenhuma sala caiu.",
        "Em falha ampla, desative temporariamente a exigência, corrija as salas e refaça a validação.",
      ] },
    ],
  },
  {
    id: "firmware-usb",
    titulo: "Firmware por USB e recuperação do ESP32",
    papel: "superadmin",
    categoria: "super_dispositivos",
    tags: ["PlatformIO", "flash", "LittleFS", "serial", "erase"],
    corpo: [
      { t: "comando", titulo: "Fluxo automatizado", comandos: C.firmwareUsb.slice(0, 3), quando: "Primeira gravação, atualização local ou recuperação que não depende de OTA.", preRequisitos: "PlatformIO ou capacidade do flash.sh de instalá-lo; cabo USB de dados; permissão na porta serial.", resultado: "Compila, grava data/ em LittleFS e grava o firmware; com várias portas, informe a porta explicitamente.", risco: "O fluxo automatizado não apaga a flash inteira, mas substitui firmware e LittleFS." },
      { t: "comando", titulo: "Passos manuais do PlatformIO", comandos: C.firmwareUsb.slice(3), quando: "Diagnóstico fino, gravação por etapas ou monitor serial.", preRequisitos: "Execute em remoteifes-esp32; selecione a porta com -p quando necessário.", resultado: "Compilação, gravação de arquivos, gravação da aplicação ou logs a 115200 baud, conforme a linha.", risco: "pio run --target erase apaga toda a flash, inclusive rede e configuração; use só quando a limpeza total for intencional." },
      { t: "passos", itens: [
        "Antes de erase, registre sala/MAC e garanta dados de rede, servidor e credencial para reprovisionar.",
        "Após gravar, acompanhe o boot no monitor serial e procure versão, Wi-Fi e WebSocket.",
        "Refaça setup AP e vínculo se foram apagados; depois valide controle e telemetria.",
      ] },
      { t: "nota", texto: "A gravação USB é a recuperação de referência quando OTA não inicia ou reverte repetidamente. Ela regrava o slot ativo sem depender do servidor." },
    ],
  },
  {
    id: "firmware-ota",
    titulo: "Publicar e acompanhar firmware OTA",
    papel: "superadmin",
    categoria: "super_dispositivos",
    tags: ["firmware", "OTA", "SHA-256", "versão", "rollback"],
    verNoApp: "/admin/esp32",
    corpo: [
      { t: "comando", titulo: "Compilar e publicar a imagem", comandos: C.firmwareOta, quando: "Depois de validar o firmware e antes de oferecer OTA às salas.", preRequisitos: "PlatformIO; execute as duas últimas linhas em remoteifes-server; a versão deve corresponder ao firmware e seguir x.y.z.", resultado: "firmware.bin válido (64 KiB–3 MiB), SHA-256 e manifesto atômico passam a representar a única versão publicada.", risco: "Publicar troca a oferta para todos; valide em bancada e preserve o caminho USB de recuperação." },
      { t: "passos", itens: [
        "Em <strong>Administração &gt; Dispositivos &gt; Firmware / OTA</strong>, compare a versão publicada com a instalada e escolha primeiro uma sala piloto conectada.",
        "Use a ação OTA. O servidor limita a duas atualizações simultâneas e recusa downgrade, versão já instalada ou uma segunda operação na mesma sala.",
        "Acompanhe ofertado, baixando, gravado e reiniciando. A conclusão exige a placa voltar e reportar a versão nova; falha ou versão antiga indica erro/reversão.",
        "Valide conexão, telemetria e comandos na sala piloto antes de avançar em lotes pequenos.",
      ] },
      { t: "sub", titulo: "Distribuição em etapas para vários dispositivos" },
      { t: "p", texto: "No mesmo painel, <strong>Distribuição em etapas</strong> atualiza um conjunto de ESP32 sem abrir mão das garantias da OTA avulsa: cada sala recebe a mesma oferta, confere o SHA-256, grava no slot ocioso e só conta como validada quando reconecta reportando a versão nova. A ação por sala continua disponível como caminho simples." },
      { t: "fluxo", titulo: "Etapas da distribuição", itens: [
        { tipo: "screen", texto: "Selecionar dispositivos" },
        { tipo: "server", texto: "Verificar compatibilidade" },
        { tipo: "device", texto: "Canário" },
        { tipo: "status", texto: "Validar o canário" },
        { tipo: "device", texto: "Lotes controlados" },
        { tipo: "status", texto: "Concluída ou interrompida" },
      ] },
      { t: "passos", itens: [
        "Marque as salas aptas. Quem já está na versão publicada ou reporta versão maior aparece com o motivo e não é atualizado; quem está desconectado, em modo de configuração ou com OTA avulsa em andamento espera a própria vez.",
        "Escolha o canário e o tamanho do lote (1 a 5). O teto de duas atualizações simultâneas continua valendo; lotes maiores apenas enfileiram dentro do lote.",
        "Acompanhe a etapa e o estado de cada dispositivo. Os lotes só começam depois que o canário volta validado, e uma falha real em qualquer lote interrompe a distribuição.",
        "Use <strong>Pausar</strong> para impedir novos inícios sem interromper quem está gravando, <strong>Retomar</strong> para seguir do lote seguinte e <strong>Cancelar o que não começou</strong> para encerrar apenas a fila.",
        "Antes de continuar depois de uma parada, valide conexão, telemetria e comandos das salas já atualizadas e leia o motivo registrado.",
      ] },
      { t: "tabela", cabecalho: ["Estado do dispositivo", "Significado"], linhas: [
        ["validado", "reconectou reportando a versão publicada — é o único desfecho contado como sucesso"],
        ["falhou", "erro reportado, conexão perdida ou timeout durante a transferência; não comprova que a gravação não ocorreu"],
        ["sem confirmação", "retorno ausente ou versão inesperada, ou registro da tentativa indisponível; não comprova rollback e exige conferência"],
        ["não atualizado", "inapto na verificação ou offline além da espera; nunca é tratado como sucesso"],
      ] },
      { t: "nota", texto: "A distribuição não muda o protocolo do ESP32 nem exige firmware novo: ela usa as mesmas mensagens de oferta, progresso e resultado que a frota atual já entende. Reiniciar o servidor no meio não repete oferta — o andamento é reconciliado pelo estado de OTA persistido." },
      { t: "nota", nivel: "atencao", texto: "A reversão é do próprio ESP32, pelo esquema A/B. O servidor não guarda a imagem anterior e não consegue reinstalá-la: ele registra a versão inesperada e interrompe a distribuição sem afirmar que houve reversão. Uma imagem ruim se corrige publicando uma versão maior e corrigida ou regravando por USB." },
      { t: "p", texto: "O ESP32 confere tamanho e SHA-256 antes de gravar. A imagem usa partições A/B e tem até 90 segundos após iniciar para validar Wi-Fi e WebSocket; a reversão depende de suporte no bootloader instalado. O servidor mantém o estado por reinício e aplica timeouts de transferência e retorno." },
      { t: "nota", nivel: "atencao", texto: "OTA preserva NVS e vínculo da sala, mas sempre pode exigir recuperação física. Não atualize todos os dispositivos ao mesmo tempo e não desligue energia durante download/gravação." },
      { t: "links", itens: [{ id: "firmware-usb", texto: "Recuperar por USB" }, { id: "monitoramento", texto: "Investigar falha e notificações" }, { id: "esp32-cadastro", texto: "Cadastro do dispositivo na sala" }] },
    ],
  },
];
