const C = require("./commands");

module.exports = [
  {
    id: "operacao-admin",
    titulo: "Operação, implantação e manutenção",
    papel: "superadmin",
    categoria: "super_infra",
    tags: ["manutenção", "normal", "destrutivo", "release", "infraestrutura"],
    corpo: [
      { t: "tabela", cabecalho: ["Classe", "Exemplos e disciplina"], linhas: [
        ["Operação normal", "status/health, logs, notificações e controle das salas"],
        ["Manutenção", "backup, dependências, serviço, firmware, configuração e testes em janela"],
        ["Destrutivo/reset", "restore, erase, exclusões, reset de Wi-Fi e clear.py; exige alvo conferido e recuperação pronta"],
        ["Release/deploy", "versão de servidor, PWA, firmware ou APK; validação e rollback próprios"],
      ] },
      { t: "fluxo", titulo: "Mudança segura", itens: [
        { tipo: "status", texto: "Escopo, impacto e pré-requisitos" },
        { tipo: "action", texto: "Backup e estado anterior" },
        { tipo: "action", texto: "Mudança em janela controlada" },
        { tipo: "status", texto: "Health + fluxo funcional" },
        { tipo: "decision", texto: "Aceitar ou recuperar" },
      ] },
      { t: "nota", nivel: "seguranca", texto: "Execute no host e diretório indicados, com conta autorizada. Não cole .env, tokens, banco, keystore, senhas, deviceId+segredo ou chaves privadas no manual, logs compartilhados ou relatos." },
      { t: "links", itens: [{ id: "instalacao-servidor", texto: "Instalação inicial" }, { id: "backup-restauracao", texto: "Backup e restauração" }, { id: "implantacao-rollback", texto: "Deploy e rollback" }, { id: "diagnostico-testes", texto: "Diagnóstico e testes" }] },
    ],
  },
  {
    id: "instalacao-servidor",
    titulo: "Instalação e inicialização do servidor",
    papel: "superadmin",
    categoria: "super_infra",
    tags: ["setup", "Node", "SQLite", "primeiro acesso", "produção"],
    corpo: [
      { t: "comando", titulo: "Instalação rápida em macOS/Linux", comandos: C.instalacao, quando: "Primeira instalação ou ambiente de desenvolvimento integrado.", preRequisitos: "Clone completo; bash; rede para baixar Node/dependências quando ausentes.", resultado: "Node 22.13+ é verificado/instalado, dependências são instaladas, .env.example vira .env somente se ainda não existir, e o servidor inicia em 8080 por padrão.", risco: "Revise .env antes de produção; setup não sobrescreve um .env existente." },
      { t: "p", texto: "O primeiro startup cria/migra o SQLite e semeia as salas. Não existe comando separado de migração. Se <code>SENHA_ADMIN_INICIAL</code> estiver vazia em banco novo, a conta inicial é <strong>superadmin/admin</strong> e exibe aviso persistente para troca." },
      { t: "comando", titulo: "Startup e desenvolvimento", comandos: C.desenvolvimento, quando: "npm start para operação supervisionada; npm run dev somente durante desenvolvimento do servidor.", preRequisitos: "Execute em remoteifes-server com .env revisado.", resultado: "Express serve website, API e WebSockets na mesma origem; dev reinicia ao alterar arquivos do servidor.", risco: "Não use npm run dev como gerenciador de produção e não abra uma segunda instância sobre o mesmo banco." },
      { t: "nota", texto: "Em Windows, o README orienta npm install e cópia manual de .env.example, porque npm run setup usa bash. Produção Linux/Raspberry Pi deve seguir systemd." },
    ],
  },
  {
    id: "servico-systemd",
    titulo: "Serviço systemd e health check",
    papel: "superadmin",
    categoria: "super_infra",
    tags: ["systemd", "journalctl", "health", "watchdog", "Raspberry Pi"],
    corpo: [
      { t: "comando", titulo: "Instalar e operar o serviço", comandos: C.servico, quando: "Primeiro provisionamento Linux/Raspberry Pi e operação diária.", preRequisitos: "npm run setup concluído; sudo; .env e diretório persistente revisados.", resultado: "remoteifes.service inicia no boot e reinicia em falha; o timer de health verifica a cada 2 min e recupera após 3 falhas consecutivas.", risco: "Pare o serviço antes de restore. Toda alteração de .env exige restart." },
      { t: "p", texto: "<code>npm run health</code> consulta o endpoint local: HTTP 200 com banco ok indica saúde mínima; 503 indica banco indisponível. ESP32 offline não derruba o health, portanto valide dispositivos separadamente." },
      { t: "passos", itens: [
        "Em incidente, confira status, depois journalctl e health.",
        "Corrija a causa antes de reiniciar repetidamente: .env, porta, banco, permissão ou disco.",
        "Após restart, confirme health, login, WebSocket/status de salas e Monitoramento.",
      ] },
    ],
  },
  {
    id: "servidor-rede",
    titulo: "Rede, proxy, HTTPS e configuração do host",
    papel: "superadmin",
    categoria: "super_infra",
    tags: ["CIDR", "Nginx", "HTTPS", "CORS", "TRUST_PROXY", "BIND_ADDR", ".env"],
    corpo: [
      { t: "comando", titulo: "Redes autorizadas", comandos: C.redes, quando: "Antes de liberar produção ou ao mudar faixas institucionais.", preRequisitos: "Execute em remoteifes-server com o mesmo .env do serviço; use CIDRs reais, não os exemplos.", resultado: "A lista é gravada/mostrada e passa a valer após restart. localhost e rotas de dispositivo seguem regras próprias.", risco: "Definir a lista substitui a configuração atual; um CIDR errado bloqueia usuários ou amplia acesso." },
      { t: "comando", titulo: "Proxy reverso", comandos: C.proxy, quando: "lan-setup para Nginx local na porta 80; https-setup para domínio público com certificado.", preRequisitos: "Serviço systemd funcional; host dedicado; para HTTPS, DNS e Internet válidos.", resultado: "Nginx encaminha HTTP e WebSocket, Node passa a 127.0.0.1 e TRUST_PROXY=1; HTTPS configura Certbot e renovação.", risco: "Não exponha também a porta interna 8080. Confira exatamente um proxy confiável antes de usar TRUST_PROXY=1." },
      { t: "tabela", cabecalho: ["Configuração de .env", "Finalidade operacional"], linhas: [
        ["NODE_ENV / PORTA / BIND_ADDR", "ambiente, porta e interface de escuta; atrás do proxy use 127.0.0.1"],
        ["SERVIR_FRONTEND / FRONTEND_DIR", "website servido pelo Express e eventual fonte alternativa"],
        ["CORS_ORIGIN", "origens exatas apenas quando o frontend for deliberadamente separado"],
        ["SENHA_ADMIN_INICIAL / SESSAO_MAX_HORAS", "bootstrap seguro de banco novo e limite absoluto das sessões"],
        ["TRUST_PROXY", "quantidade de proxies confiáveis; scripts Nginx ajustam para 1"],
        ["REMOTEIFES_DATA_DIR / REMOTEIFES_FIRMWARE_DIR", "dados persistentes fora do checkout e imagem OTA"],
        ["RETENCAO_DIAS_*", "limpeza automática dos históricos correspondentes"],
        ["BACKUP_AUTOMATICO / BACKUP_INTERVALO_HORAS / BACKUP_RETENCAO / BACKUP_DIR", "agenda e destino da proteção SQLite"],
        ["MOBILE_APP_RELEASE_DIR", "diretório do APK e release.json oferecidos pela página Aplicativo"],
        ["AGENDAMENTOS_MAX_ATIVOS_POR_USUARIO", "teto de agendas ativas por autor; padrão 300"],
      ] },
      { t: "p", texto: "Preserve <code>REMOTEIFES_DATA_DIR</code> fora do checkout, restrinja permissões, use <code>SERVIR_FRONTEND=true</code> para same-origin e só configure CORS para um frontend realmente separado. Não versionar .env, dados ou backups é parte da implantação." },
      { t: "comando", titulo: "Alterações incrementais ou limpeza de CIDRs", comandos: ["npm run redes -- --add 192.168.1.0/24", "npm run redes -- --clear"], quando: "--add acrescenta sem substituir; --clear esvazia deliberadamente a lista.", preRequisitos: "Confira o estado com npm run redes e mantenha um caminho localhost/SSH de recuperação.", resultado: "A lista persistida é atualizada; reinicie o serviço para a operação planejada.", risco: "Com modo de teste desligado, --clear bloqueia o acesso normal de produção, exceto regras específicas de dispositivo e localhost." },
      { t: "nota", nivel: "seguranca", texto: "HTTPS é necessário quando o tráfego sai de uma LAN administrada. Modo de teste não substitui CIDR, firewall, proxy nem TLS." },
    ],
  },
  {
    id: "backup-restauracao",
    titulo: "Backup e restauração do banco",
    papel: "superadmin",
    categoria: "super_infra",
    tags: ["backup", "restore", "SQLite", "WAL", "pre-restauração"],
    corpo: [
      { t: "comando", titulo: "Criar, listar e restaurar", comandos: C.backup, quando: "Backup manual antes de mudança; listagem/restore em recuperação planejada.", preRequisitos: "Execute em remoteifes-server com o diretório de dados correto. O servidor pode ficar no ar para backup, mas DEVE estar parado para restore.", resultado: "Backup usa snapshot consistente e é verificado/rotacionado. Restore verifica o candidato, cria pre-restauracao do banco atual, troca e revalida.", risco: "Restore sobrescreve o banco ativo. <arquivo> pode ser nome em BACKUP_DIR ou caminho completo; --sim pula confirmação e deve ser restrito à automação revisada." },
      { t: "passos", itens: [
        "Confirme Monitoramento, espaço em disco e o caminho do diretório de dados.",
        "Crie um backup rotulado antes da mudança e copie backups críticos para armazenamento externo autorizado.",
        "Para restaurar, pare remoteifes.service, liste e confira o arquivo e então execute a restauração.",
        "Inicie o serviço, rode health e valide login, contas, agendas, salas e ESP32. Preserve o pre-restauracao até aceitar o resultado.",
      ] },
      { t: "nota", nivel: "atencao", texto: "Não copie apenas remoteifes.db enquanto ignora o WAL. Teste restauração periodicamente em ambiente separado; existência de arquivo não prova recuperabilidade." },
    ],
  },
  {
    id: "implantacao-rollback",
    titulo: "Implantação, atualização e rollback",
    papel: "superadmin",
    categoria: "super_infra",
    tags: ["deploy", "rollback", "origin/main", "offline", "pre-update"],
    corpo: [
      { t: "comando", titulo: "Deploy e rollback protegidos", comandos: C.deploy.slice(0, 5), quando: "Deploy de origin/main/tag e retorno manual à versão anterior ou ref conhecido.", preRequisitos: "Clone de produção; main sem mudanças locais; serviço instalado; dados persistentes; ref já local para --offline.", resultado: "Deploy cria pre-update, resolve o ref, instala dependências se mudaram, reinicia e exige health; falha aciona rollback automático. Rollback cria pre-rollback e verifica health.", risco: "--force permite descartar mudanças locais. Rollback troca código, não desfaz esquema do banco; restaure o pre-update compatível se a versão antiga não abrir o banco migrado." },
      { t: "p", texto: "Opções avançadas do script atual: <code>bash deploy.sh [&lt;ref&gt;] [--offline] [--force] [--no-restart]</code> e <code>bash rollback.sh [&lt;ref&gt;] [--offline] [--no-restart]</code>. Use <code>--force</code> só depois de revisar o diff que será descartado; <code>--no-restart</code> também pula health e transfere a validação para o operador." },
      { t: "fluxo", titulo: "Atualização protegida", itens: [
        { tipo: "status", texto: "Árvore limpa + backup" },
        { tipo: "action", texto: "Resolver origin/main, tag ou ref local" },
        { tipo: "action", texto: "Trocar código e dependências" },
        { tipo: "status", texto: "Restart + health" },
        { tipo: "decision", texto: "Sucesso ou rollback automático" },
        { tipo: "status", texto: "Validar funções e dispositivos" },
      ] },
      { t: "p", texto: "Depois do health, valide login, uma consulta e um comando em sala piloto, agenda, WebSocket, Monitoramento e versão da PWA. Leia deploy.log e os arquivos current-version/previous-version no diretório de dados." },
    ],
  },
  {
    id: "release-servidor",
    titulo: "Criar uma versão do servidor",
    papel: "superadmin",
    categoria: "super_infra",
    tags: ["release.sh", "tag", "package.json", "push"],
    corpo: [
      { t: "comando", titulo: "Marcar release", comandos: C.deploy.slice(5), quando: "Na máquina de desenvolvimento, quando main validada estiver pronta para uma versão x.y.z.", preRequisitos: "Branch main, árvore limpa, testes concluídos e autorização para commit/tag/push.", resultado: "Atualiza package.json, cria commit e tag vX.Y.Z e, após confirmação, envia ao remoto.", risco: "Não execute no host de produção com alterações locais. Tag publicada deve ser tratada como imutável." },
      { t: "p", texto: "A versão do servidor, a versão do frontend/PWA, a versão do firmware e versionName/versionCode Android têm ciclos distintos. Não reutilize uma delas como substituta automática das outras." },
    ],
  },
  {
    id: "recuperacao-superadmin",
    titulo: "Recuperar a senha do Superadministrador",
    papel: "superadmin",
    categoria: "super_infra",
    tags: ["reset-admin", "senha", "sessões"],
    corpo: [
      { t: "comando", titulo: "Redefinir no host", comandos: C.recuperacaoConta, quando: "Quando o login Superadministrador não puder ser recuperado pela interface.", preRequisitos: "Acesso autorizado ao host e ao mesmo .env/banco; execute em remoteifes-server.", resultado: "Define a senha escolhida ou, sem argumento, restaura admin; nenhuma senha é impressa e todas as sessões são encerradas.", risco: "Sem argumento volta a uma senha pública e fraca. Entre imediatamente, troque-a e verifique acesso ao host." },
    ],
  },
];
