const C = require("./commands");

// Infrastructure, from the Superadministrator's point of view.
//
// Responsibility split:
//   - the **Console** owns routine host procedures: service, update, rollback, backup, restore,
//     account recovery, network diagnostics and mobile/CI. The manual states where each function
//     lives, what it does, who may run it, its impact and what to do on failure, without repeating
//     the command-line tutorial;
//   - the **README** owns first installation, the security model and the single terminal recovery
//     reference, which must work without the Console and without the application;
//   - only procedures the Console deliberately does not run stay on the terminal and are therefore
//     documented with commands here: proxy/HTTPS, release tagging and first installation.

module.exports = [
  {
    id: "operacao-admin",
    titulo: "Operação, implantação e manutenção",
    papel: "superadmin",
    categoria: "super_infra",
    tags: ["manutenção", "normal", "destrutivo", "release", "infraestrutura", "console"],
    corpo: [
      { t: "p", texto: "A manutenção de rotina do servidor e do host acontece no <strong>Console de Operações</strong>, um serviço local separado do RemoteIFES. A operação do prédio — salas, agendamentos, contas e ESP32 — continua nesta aplicação." },
      { t: "tabela", cabecalho: ["Classe", "Onde fica e disciplina"], linhas: [
        ["Operação normal", "nesta aplicação: status/health, logs, notificações e controle das salas"],
        ["Manutenção", "Console de Operações: serviço, backup, atualização, dependências e configuração em janela"],
        ["Destrutivo/reset", "restauração de banco e reinício de host no console, com reautenticação; erase, exclusões e clear.py seguem no terminal"],
        ["Release/deploy", "implantação e rollback no console; criar uma versão (tag) continua na máquina de desenvolvimento"],
      ] },
      { t: "fluxo", titulo: "Mudança segura", itens: [
        { tipo: "status", texto: "Escopo, impacto e pré-requisitos" },
        { tipo: "action", texto: "Backup e estado anterior" },
        { tipo: "action", texto: "Mudança em janela controlada" },
        { tipo: "status", texto: "Health + fluxo funcional" },
        { tipo: "decision", texto: "Aceitar ou recuperar" },
      ] },
      { t: "nota", nivel: "seguranca", texto: "Execute no host e diretório indicados, com conta autorizada. Não cole .env, tokens, banco, keystore, senhas, deviceId+segredo ou chaves privadas no manual, logs compartilhados ou relatos." },
      { t: "links", itens: [
        { id: "console-operacoes", texto: "Console de Operações" },
        { id: "instalacao-servidor", texto: "Instalação inicial" },
        { id: "backup-restauracao", texto: "Backup e restauração" },
        { id: "implantacao-rollback", texto: "Deploy e rollback" },
        { id: "diagnostico-testes", texto: "Diagnóstico e testes" },
      ] },
    ],
  },
  {
    id: "console-operacoes",
    titulo: "Console de Operações",
    papel: "superadmin",
    categoria: "super_infra",
    tags: ["console", "manutenção", "host", "acesso", "SSH", "socket"],
    corpo: [
      { t: "p", texto: "O console é um serviço local que administra <strong>o RemoteIFES, o host e a infraestrutura</strong>. Ele tem identidade própria: a conta do console não é a do Superadministrador da aplicação, porque a autenticação da aplicação depende do banco e é encerrada a cada reinício — justamente quando a recuperação é necessária." },
      { t: "tabela", cabecalho: ["Área do console", "O que resolve"], linhas: [
        ["Visão geral", "estado da aplicação, do serviço, do watchdog e do host, com o que exige atenção em primeiro lugar"],
        ["Serviço", "reiniciar, parar e iniciar o RemoteIFES; ler o journal das unidades"],
        ["Atualizações", "comparar versão em execução, checkout e origin; implantar um commit revisado; reverter"],
        ["Dados e recuperação", "backup verificado, restauração com o serviço parado e recuperação da senha do Superadministrador"],
        ["Aplicativo e CI", "versões de servidor, PWA, Cordova e Android, APK publicado e estado das execuções do GitHub"],
        ["Rede e domínio", "interfaces, rotas, resolvedor, portas em escuta, proxy, DNS e validade do certificado"],
        ["Programa", "versão do próprio console, atualização e reversão do programa, capacidades da plataforma e onde a instalação mora"],
        ["Avançado", "elevação, auditoria do console, histórico de operações e Terminal Expert"],
      ] },
      { t: "comando", titulo: "Instalar o console (uma vez, no host)", comandos: C.consoleInstalar, quando: "Primeiro provisionamento, depois de o RemoteIFES já estar instalado.", preRequisitos: "Acesso root no host; Node 22.13+ no PATH; checkout completo.", resultado: "Instala o programa em /opt/remoteifes-console — camada estável mais versoes/&lt;versao&gt; —, o auxiliar privilegiado como root, a regra de sudo restrita (validada com visudo) e as unidades systemd. Exibe uma única vez o segredo para criar o primeiro operador.", risco: "Reexecutar refaz unidades e instala a versão de novo; o estado (operadores, auditoria, histórico) é preservado." },
      { t: "p", texto: "O mesmo instalador serve Linux, Windows e macOS. No Windows e no macOS não há serviço residente: o console é aberto pelo lançador, que confere a identidade de quem responde na porta antes de abrir o navegador, e sai sozinho depois de ficar ocioso. As capacidades que não existem em cada sistema aparecem na aba <strong>Programa</strong> com o motivo exato, e o servidor recusa a operação de verdade — não é só o botão que fica apagado." },
      { t: "comando", titulo: "Abrir de outra máquina", comandos: C.consoleAcesso, quando: "Sempre que a manutenção não for feita no próprio Pi.", preRequisitos: "Acesso SSH ao host.", resultado: "Encaminha a porta local do console; abra então http://127.0.0.1:8099 no seu navegador.", risco: "O <code>localhost</code> do seu computador não é o do Pi: sem o túnel, o endereço aponta para a sua própria máquina. O console escuta apenas no loopback do host." },
      { t: "passos", itens: [
        "Entre com o operador do console; operações sensíveis pedem a senha de novo e valem por poucos minutos.",
        "Antes de qualquer interrupção, leia a avaliação de impacto: ela bloqueia a operação quando há OTA em andamento ou outra manutenção, e avisa quando a atividade dos ESP32 não pode ser observada.",
        "Acompanhe a operação pela janela de progresso; fechar o navegador não interrompe o trabalho.",
        "Ao final, confira o resultado verificado: um código de saída zero não é prova de que a versão certa subiu.",
      ] },
      { t: "nota", nivel: "atencao", texto: "O console roda fora do checkout de propósito: uma atualização ou um rollback do RemoteIFES trocam o checkout inteiro e não derrubam o console. A versão do <strong>programa console</strong>, mostrada na aba Programa, é independente do commit do RemoteIFES implantado: atualizar o console baixa um artefato de release assinado e troca a versão ativa, sem usar git e sem tocar no checkout." },
      { t: "comando", titulo: "Reparar o console", comandos: C.consoleReparo, quando: "O console não abre, não sobe pelo socket ou ficou inconsistente após uma atualização.", preRequisitos: "Acesso ao host por SSH.", resultado: "Mostra o estado do socket e do serviço, os registros do console e reinstala a versão presente por cima, refazendo unidades, auxiliar e regra de sudo.", risco: "Nenhum para o RemoteIFES: reinstalar o console não toca no serviço da aplicação nem no banco." },
      { t: "comando", titulo: "Remover o console", comandos: C.consoleRemover, quando: "O console não será mais usado neste host.", preRequisitos: "Acesso root no host.", resultado: "A simulação lista exatamente o que sairia; a remoção tira unidades, auxiliar, regra de sudo, atalhos e o programa. O estado (operadores, auditoria, histórico) é PRESERVADO, e só sai com --apagar-estado.", risco: "O checkout do RemoteIFES, o banco, os backups e o serviço da aplicação não são tocados. A remoção recusa qualquer caminho que não prove ser uma instalação do console." },
      { t: "nota", nivel: "seguranca", texto: "O Terminal Expert é uma capacidade à parte, com destravamento e reautenticação. Um operador autorizado que use sudo tem o alcance que o host lhe der, inclusive alterar o próprio console e seus registros: o objetivo do desenho é impedir acesso não autorizado e uso acidental, não tornar o software imutável diante do root." },
      { t: "links", itens: [{ id: "implantacao-rollback", texto: "Deploy e rollback" }, { id: "backup-restauracao", texto: "Backup e restauração" }, { id: "recuperacao-superadmin", texto: "Recuperar o Superadministrador" }] },
    ],
  },
  {
    id: "instalacao-servidor",
    titulo: "Instalação e inicialização do servidor",
    papel: "superadmin",
    categoria: "super_infra",
    tags: ["setup", "Node", "SQLite", "primeiro acesso", "produção"],
    corpo: [
      { t: "comando", titulo: "Instalação rápida em macOS/Linux", comandos: C.instalacao, quando: "Primeira instalação ou ambiente de desenvolvimento integrado.", preRequisitos: "Clone completo; bash; rede para baixar Node/dependências quando ausentes.", resultado: "Node 22.13+ é verificado/instalado, dependências são instaladas, .env.example vira .env somente se ainda não existir, e o servidor inicia em 8080 por padrão.", risco: "Revise .env antes de produção; setup não sobrescreve um .env existente." },
      { t: "p", texto: "O primeiro startup cria/migra o SQLite e semeia as salas. Não existe comando separado de migração. Se <code>SENHA_ADMIN_INICIAL</code> estiver vazia em banco novo, a conta inicial é <strong>superadmin/admin</strong> e exibe aviso persistente para troca." },
      { t: "comando", titulo: "Iniciar (todas as vezes seguintes)", comandos: C.iniciar, quando: "Operação supervisionada ou validação manual; em Linux/Raspberry Pi, o serviço systemd faz isso sozinho e o ciclo de vida do dia a dia fica no console.", preRequisitos: "Instalação já feita; execute em remoteifes-server com .env revisado.", resultado: "Express serve website, API e WebSockets na mesma origem, em 8080 por padrão.", risco: "Não abra uma segunda instância sobre o mesmo banco: se a porta estiver ocupada, use ou pare a instância existente." },
      { t: "comando", titulo: "Desenvolvimento do servidor (em vez de npm start)", comandos: C.desenvolvimento, quando: "Somente enquanto se altera o código do servidor.", preRequisitos: "Os mesmos de npm start; não deixe npm start rodando ao mesmo tempo.", resultado: "O mesmo conjunto integrado, reiniciando o processo ao alterar arquivos do servidor.", risco: "Não use npm run dev como gerenciador de produção." },
      { t: "comando", titulo: "Instalar o serviço systemd (uma vez)", comandos: C.servicoInstalar, quando: "Primeiro provisionamento Linux/Raspberry Pi, antes de instalar o console.", preRequisitos: "npm run setup concluído; sudo; .env e diretório persistente revisados. Execute em remoteifes-server.", resultado: "remoteifes.service inicia no boot e reinicia em falha; o timer de health verifica a cada 2 min e recupera após 3 falhas consecutivas; o instalador grava NODE_ENV=production e pergunta as redes autorizadas.", risco: "Reexecutar refaz as unidades do systemd; confira o .env antes." },
      { t: "nota", texto: "Em Windows, o README orienta npm install e cópia manual de .env.example, porque npm run setup usa bash. Produção Linux/Raspberry Pi deve seguir systemd e o Console de Operações." },
      { t: "links", itens: [{ id: "console-operacoes", texto: "Console de Operações" }] },
    ],
  },
  {
    id: "servico-systemd",
    titulo: "Serviço, watchdog e registros",
    papel: "superadmin",
    categoria: "super_infra",
    tags: ["systemd", "journalctl", "health", "watchdog", "Raspberry Pi", "console"],
    corpo: [
      { t: "p", texto: "Reiniciar, parar e iniciar o RemoteIFES, acompanhar o watchdog e ler os registros do sistema são funções do <strong>Console de Operações &gt; Serviço</strong>. Cada ação mostra o impacto antes de executar e confirma o resultado depois." },
      { t: "tabela", cabecalho: ["Ação no console", "Impacto e confirmação"], linhas: [
        ["Verificar saúde agora", "somente leitura: banco, ambiente, commit em execução e tempo no ar"],
        ["Reiniciar o RemoteIFES", "interrupção curta; todas as sessões de usuário caem e os ESP32 reconectam. O console só declara sucesso quando o /health volta saudável"],
        ["Parar o RemoteIFES", "o watchdog é desligado junto, senão ele reiniciaria a aplicação em poucos minutos. Exige digitar a confirmação"],
        ["Iniciar o RemoteIFES", "sobe o serviço e religa o watchdog; confirma pelo /health"],
        ["Registros do sistema", "journal das unidades da aplicação, do watchdog, do console e da recuperação"],
      ] },
      { t: "p", texto: "O health é um indicador mínimo: HTTP 200 com banco ok. ESP32 offline <strong>não</strong> derruba o health, então valide dispositivos separadamente em Status. Uma parada do serviço, por si só, não é uma parada durável: sem desligar o timer de saúde, o watchdog reinicia a aplicação após 3 falhas seguidas em intervalos de 2 minutos." },
      { t: "passos", itens: [
        "Em incidente, abra a Visão geral do console: ela lista primeiro o que exige atenção.",
        "Leia os registros da unidade envolvida antes de reiniciar; corrija a causa (.env, porta, banco, permissão ou disco) em vez de reiniciar repetidamente.",
        "Após o restart, confirme health, login, WebSocket/status de salas e Monitoramento nesta aplicação.",
      ] },
      { t: "nota", nivel: "atencao", texto: "Se o console estiver indisponível, os mesmos controles continuam acessíveis por terminal. A referência única desses comandos está no README, em Recuperação de emergência." },
      { t: "links", itens: [{ id: "console-operacoes", texto: "Console de Operações" }] },
    ],
  },
  {
    id: "servidor-rede",
    titulo: "Rede, proxy, HTTPS e configuração do host",
    papel: "superadmin",
    categoria: "super_infra",
    tags: ["CIDR", "Nginx", "HTTPS", "CORS", "TRUST_PROXY", "BIND_ADDR", ".env"],
    corpo: [
      { t: "p", texto: "O diagnóstico — interfaces, rotas, resolvedor, portas em escuta, proxy, DNS do domínio e validade do certificado — fica em <strong>Console de Operações &gt; Rede e domínio</strong>, sob demanda. As <strong>faixas de rede autorizadas</strong> e o <strong>modo de teste</strong> são editados só no console, em <strong>Rede e domínio &gt; Acesso à aplicação</strong>, com reautenticação e auditoria (autor <code>console:&lt;operador&gt;</code>): eles decidem quem alcança o site, e o console, fora dessa restrição, continua disponível para desfazer uma faixa errada. Em <strong>Administração &gt; Sistema &gt; Configurações</strong> os dois aparecem apenas para consulta. O modo de manutenção continua sendo editado aqui." },
      { t: "nota", nivel: "atencao", texto: "Uma requisição do próprio host para o domínio público não prova alcance externo: ela pode passar por /etc/hosts, DNS interno ou loopback. O console identifica o ponto de vista de cada sonda; para confirmar acesso externo, teste de um dispositivo fora da rede." },
      { t: "comando", titulo: "Proxy reverso e HTTPS (continuam no terminal)", comandos: C.proxy, quando: "lan-setup para Nginx local na porta 80; https-setup para domínio público com certificado.", preRequisitos: "Serviço systemd funcional; host dedicado; para HTTPS, DNS e Internet válidos.", resultado: "Nginx encaminha HTTP e WebSocket, Node passa a 127.0.0.1 e TRUST_PROXY=1; HTTPS configura Certbot e renovação.", risco: "Estes scripts instalam pacotes, sobrescrevem o site Nginx do RemoteIFES, mexem nos sites habilitados, alteram o .env e recarregam serviços. Em instalação administrada ou com vários sites, revise antes. Não exponha também a porta interna 8080 e confirme que há exatamente um proxy confiável antes de TRUST_PROXY=1." },
      { t: "comando", titulo: "Redes autorizadas pelo terminal (emergência)", comandos: C.redes, quando: "Quando o Console de Operações não estiver instalado ou acessível — por exemplo, se a faixa gravada bloqueou o próprio acesso e não há túnel SSH para o console.", preRequisitos: "Execute em remoteifes-server com o mesmo .env do serviço; use CIDRs reais, não os exemplos.", resultado: "A lista é gravada/mostrada e passa a valer na requisição seguinte. localhost e rotas de dispositivo seguem regras próprias.", risco: "Definir a lista substitui a configuração atual; um CIDR errado bloqueia usuários ou amplia acesso. O caminho gerenciado desta configuração é o Console de Operações." },
      { t: "tabela", cabecalho: ["Configuração de .env", "Finalidade operacional"], linhas: [
        ["NODE_ENV / PORTA / BIND_ADDR", "ambiente, porta e interface de escuta; atrás do proxy use 127.0.0.1"],
        ["SERVIR_FRONTEND / FRONTEND_DIR", "website servido pelo Express e eventual fonte alternativa"],
        ["CORS_ORIGIN", "origens exatas apenas quando o frontend for deliberadamente separado"],
        ["SENHA_ADMIN_INICIAL / SESSAO_MAX_HORAS", "bootstrap seguro de banco novo e limite absoluto das sessões"],
        ["TRUST_PROXY", "quantidade de proxies confiáveis; scripts Nginx ajustam para 1"],
        ["REMOTEIFES_DATA_DIR / REMOTEIFES_FIRMWARE_DIR", "dados persistentes fora do checkout e imagem OTA"],
        ["RETENCAO_DIAS_*", "limpeza automática dos históricos correspondentes"],
        ["BACKUP_AUTOMATICO / BACKUP_INTERVALO_HORAS / BACKUP_RETENCAO / BACKUP_DIR", "agenda e destino da proteção SQLite"],
        ["MOBILE_APP_RELEASE_DIR", "diretório do APK e release.json oferecidos pela página Aplicativo"],
        ["AGENDAMENTOS_MAX_ATIVOS_POR_USUARIO", "teto de agendas ativas por autor; padrão 300"],
      ] },
      { t: "p", texto: "Preserve <code>REMOTEIFES_DATA_DIR</code> fora do checkout, restrinja permissões, use <code>SERVIR_FRONTEND=true</code> para same-origin e só configure CORS para um frontend realmente separado. Não versionar .env, dados ou backups é parte da implantação. <code>TRUST_PROXY</code> é fronteira de segurança: com valor maior que zero, o servidor passa a confiar em <code>X-Forwarded-For</code> para identificar o cliente, e isso decide a restrição por faixa e o limite de tentativas." },
      { t: "p", texto: "O verificador de faixas trabalha com IPv4 em notação CIDR. Endereços IPv6 mapeados (<code>::ffff:</code>) são normalizados e <code>::1</code> equivale a <code>127.0.0.1</code>; faixas IPv6 próprias não são suportadas pelo analisador atual." },
      { t: "nota", nivel: "seguranca", texto: "HTTPS é necessário quando o tráfego sai de uma LAN administrada. Modo de teste não substitui CIDR, firewall, proxy nem TLS. A política de exposição do console é separada da política de rede da aplicação: o console escuta apenas no loopback e é alcançado por túnel SSH." },
    ],
  },
  {
    id: "backup-restauracao",
    titulo: "Backup e restauração do banco",
    papel: "superadmin",
    categoria: "super_infra",
    tags: ["backup", "restore", "SQLite", "WAL", "pre-restauração", "console"],
    corpo: [
      { t: "p", texto: "Criar backup, listar e restaurar ficam em <strong>Console de Operações &gt; Dados e recuperação</strong>. O backup roda com o servidor no ar; a restauração é destrutiva, exige reautenticação e digitar a confirmação." },
      { t: "tabela", cabecalho: ["Operação no console", "Garantias"], linhas: [
        ["Criar backup", "snapshot consistente com VACUUM INTO (sem copiar arquivo ativo), verificação de integridade e de chaves estrangeiras, permissão restrita e rotação"],
        ["Restaurar", "valida o candidato antes de tocar em qualquer coisa, desliga o watchdog, para a aplicação, confirma que o /health parou de responder, preserva o banco atual como pre-restauração, instala e revalida"],
        ["Banco corrompido", "os arquivos danificados vão para quarentena com sufixo .corrompido-&lt;data&gt;, junto de -wal e -shm; nada é apagado"],
      ] },
      { t: "nota", nivel: "atencao", texto: "Restaurar descarta toda a atividade do prédio registrada depois do backup escolhido: comandos, agendamentos, relatos, auditoria e contas criadas no intervalo. Reverter código e restaurar banco são decisões separadas." },
      { t: "p", texto: "<strong>Escopo do backup:</strong> ele contém o banco SQLite, inclusive as credenciais dos dispositivos. Não contém <code>.env</code>, firmware, APKs, material TLS, identidade do console nem configuração do host. Um backup de banco não é, sozinho, plano de recuperação de desastre: guarde separadamente o <code>.env</code> e a configuração do host, em local autorizado." },
      { t: "p", texto: "Restaurar dados antigos pode deixar as credenciais dos ESP32 diferentes das gravadas na NVS das placas: dispositivos podem precisar de nova credencial depois da restauração." },
      { t: "passos", itens: [
        "Crie um backup rotulado antes de qualquer mudança e copie os críticos para armazenamento externo autorizado.",
        "Para restaurar, confira o arquivo na lista e leia a avaliação de impacto antes de confirmar.",
        "Depois da restauração, valide login, contas, agendas, salas e ESP32. Preserve a cópia pre-restauração até aceitar o resultado.",
        "Teste restauração periodicamente em ambiente separado: a existência do arquivo não prova recuperabilidade.",
      ] },
      { t: "nota", texto: "Com o console indisponível, <code>npm run restore</code> continua funcionando no terminal, com o servidor parado. O README traz a referência única desse caminho." },
      { t: "links", itens: [{ id: "console-operacoes", texto: "Console de Operações" }] },
    ],
  },
  {
    id: "implantacao-rollback",
    titulo: "Implantação, atualização e rollback",
    papel: "superadmin",
    categoria: "super_infra",
    tags: ["deploy", "rollback", "origin/main", "offline", "pre-update", "console"],
    corpo: [
      { t: "p", texto: "Atualizar e reverter ficam em <strong>Console de Operações &gt; Atualizações</strong>. A tela separa explicitamente coisas que costumam ser confundidas em um único número de versão." },
      { t: "tabela", cabecalho: ["O que a tela distingue", "Por que importa"], linhas: [
        ["Commit do processo em execução", "é o que está realmente no ar; vem do /health, não do disco"],
        ["HEAD do checkout e sujeira", "um deploy interrompido, um git pull manual ou --no-restart deixam o disco à frente do processo"],
        ["Ramo local e upstream", "revela HEAD destacado e clone raso"],
        ["Último origin/main observado", "mostra a hora da observação; dado antigo é exibido como antigo, nunca como atual"],
        ["Última implantação verificada", "vem do registro de deploy, com sucesso ou falha"],
      ] },
      { t: "p", texto: "O alvo escolhido é fixado em um commit exato: confirmação, pré-verificação, execução e verificação final ficam presas a ele, e um commit que apareça em origin depois da confirmação não é implantado silenciosamente. Alterações locais não commitadas <strong>recusam</strong> a atualização — o console nunca usa <code>--force</code>." },
      { t: "fluxo", titulo: "Atualização protegida", itens: [
        { tipo: "status", texto: "Árvore limpa + backup" },
        { tipo: "action", texto: "Resolver o commit revisado" },
        { tipo: "action", texto: "Trocar código e dependências" },
        { tipo: "status", texto: "Restart + health" },
        { tipo: "decision", texto: "Sucesso ou rollback automático" },
        { tipo: "status", texto: "Validar funções e dispositivos" },
      ] },
      { t: "p", texto: "Sucesso exige que o processo em execução informe exatamente o commit alvo: um processo antigo que sobreviveu a um restart falho responde igual a um saudável. Uma versão alvo anterior ao campo de commit no /health só é aceita quando um processo saudável comprovadamente subiu depois do reinício, e o resultado é registrado como <strong>identidade não confirmada</strong>." },
      { t: "nota", nivel: "atencao", texto: "Reverter troca apenas o código: não desfaz migração de esquema nem devolve dados. Se a versão antiga não abrir o banco migrado, restaurar o backup pre-update é uma decisão separada e explícita — nunca automática." },
      { t: "p", texto: "A interrupção é curta, mas existe: as sessões dos usuários são encerradas e os ESP32 precisam reconectar. Não é implantação sem indisponibilidade. Depois do health, valide login, uma consulta e um comando em sala piloto, agenda, WebSocket, Monitoramento e a versão da PWA." },
      { t: "nota", texto: "Atualizar o próprio console é uma ação à parte, também no console: ele roda de fora do checkout, então trocar o checkout não o derruba." },
      { t: "links", itens: [{ id: "console-operacoes", texto: "Console de Operações" }, { id: "backup-restauracao", texto: "Backup e restauração" }] },
    ],
  },
  {
    id: "release-servidor",
    titulo: "Criar uma versão do servidor",
    papel: "superadmin",
    categoria: "super_infra",
    tags: ["release.sh", "tag", "package.json", "push"],
    corpo: [
      { t: "comando", titulo: "Marcar release", comandos: C.release, quando: "Na máquina de desenvolvimento, quando main validada estiver pronta para uma versão x.y.z.", preRequisitos: "Branch main, árvore limpa, testes concluídos e autorização para commit/tag/push.", resultado: "Atualiza package.json, cria commit e tag vX.Y.Z e, após confirmação, envia ao remoto.", risco: "Não execute no host de produção com alterações locais. Tag publicada deve ser tratada como imutável." },
      { t: "p", texto: "Criar uma versão é autoria, não implantação: é diferente de implantar uma revisão que já existe. Por isso continua fora do console, na máquina de desenvolvimento. Depois da tag publicada, a implantação no host é feita pelo console." },
      { t: "p", texto: "A versão do servidor, a versão do frontend/PWA, a versão do firmware e versionName/versionCode Android têm ciclos distintos. Não reutilize uma delas como substituta automática das outras." },
    ],
  },
  {
    id: "recuperacao-superadmin",
    titulo: "Recuperar a senha do Superadministrador",
    papel: "superadmin",
    categoria: "super_infra",
    tags: ["reset-admin", "senha", "sessões", "console"],
    corpo: [
      { t: "p", texto: "Em <strong>Console de Operações &gt; Dados e recuperação</strong>, a ação <em>Redefinir a senha do superadministrador</em> instala uma nova senha na conta de nível 3 desta aplicação. A senha é enviada no corpo da requisição e entregue ao processo por entrada padrão: não aparece em linha de comando, em <code>ps</code>, em log nem na auditoria." },
      { t: "p", texto: "A conta é escolhida pelo <strong>nível</strong>, não pelo nome: o login padrão mudou de <code>admin</code> para <code>superadmin</code> e pode ter sido renomeado. Só as sessões <strong>dessa conta</strong> são encerradas; as demais continuam válidas — um reinício do serviço é que encerra todas." },
      { t: "nota", nivel: "seguranca", texto: "A recuperação pelo console exige operador autenticado e reautenticação. Ela não define senha padrão: um valor conhecido como <code>admin</code> é recusado." },
      { t: "comando", titulo: "Redefinir pelo terminal (emergência)", comandos: C.recuperacaoConta, quando: "Console indisponível ou aplicação sem login utilizável.", preRequisitos: "Acesso autorizado ao host e ao mesmo .env/banco; execute em remoteifes-server.", resultado: "Define a senha escolhida ou, sem argumento, restaura admin; nenhuma senha é impressa e as sessões da conta são encerradas.", risco: "Sem argumento volta a uma senha pública e fraca. Entre imediatamente, troque-a e verifique o acesso ao host. O caminho do console não tem esse fallback." },
      { t: "links", itens: [{ id: "console-operacoes", texto: "Console de Operações" }] },
    ],
  },
];
