module.exports = [
  {
    id: "configuracoes-globais",
    titulo: "Configurações globais",
    papel: "superadmin",
    categoria: "super_seguranca",
    tags: ["Configurações", "sessão", "temperatura", "Turbo", "modo de teste", "manutenção", "retenção", "RemoteIFES-Setup"],
    verNoApp: "/admin/config",
    corpo: [
      { t: "p", texto: "<strong>Administração &gt; Sistema &gt; Configurações</strong> aplica política global. Leia todos os campos e registre os valores anteriores antes de salvar." },
      { t: "tabela", cabecalho: ["Grupo", "Efeito"], linhas: [
        ["Sessão por inatividade", "prazos distintos para usuários e administradores e antecedência do aviso"],
        ["Presença online", "tempo sem uso ainda classificado como online em Gestão &gt; Ativos"],
        ["Limite de temperatura", "faixa global 16–30 °C; alvos e agendas fora da nova faixa são ajustados"],
        ["Função adicional do Turbo", "nenhuma ou Oscilação vertical (Swing), aplicada junto do Turbo"],
        ["Modo de teste", "desativa temporariamente a restrição de rede em produção"],
        ["Redes autorizadas", "uma faixa CIDR por linha para acesso normal em produção"],
        ["Modo de manutenção", "bloqueia login e uso de usuários comuns; administradores continuam"],
        ["Credenciais obrigatórias", "recusa todo ESP32 que ainda se autentique somente por MAC"],
        ["Senha na rede RemoteIFES-Setup", "desligada por padrão: o AP permanente do ESP32 fica aberto. Ligada, ele passa a exigir a senha padrão do firmware. Só afeta o Wi-Fi local, não a autenticação no servidor"],
        ["Retenção", "1–365 dias para auditoria e indisponibilidade; limpeza é automática"],
      ] },
      { t: "passos", itens: [
        "Confirme a janela operacional e o impacto nos usuários/dispositivos.",
        "Altere apenas o grupo necessário e use <strong>Salvar configurações</strong>.",
        "Espere <strong>Configurações salvas</strong>. Mudanças de temperatura/Turbo propagam o estado desejado aos dispositivos configurados; sessões recebem o novo prazo.",
        "Valide Início, uma sala piloto, <strong>Gestão &gt; Ativos</strong> e <strong>Sistema &gt; Status</strong>. Em falha, restaure os valores registrados e salve novamente.",
      ] },
      { t: "nota", nivel: "seguranca", texto: "Modo de teste pode expor o sistema fora das redes autorizadas; use apenas durante um teste supervisionado e desligue em seguida. Não ative credenciais obrigatórias enquanto o Status ainda mostrar salas Só MAC. A senha do RemoteIFES-Setup é um controle separado: ative-a onde o acesso físico às salas não for controlado." },
      { t: "links", itens: [{ id: "esp32-credenciais", texto: "Migrar credenciais antes da exigência global" }, { id: "servidor-rede", texto: "Rede, proxy e HTTPS no host" }] },
    ],
  },
  {
    id: "relatos-gestao",
    titulo: "Gerenciar relatos de problemas",
    papel: "superadmin",
    categoria: "super_seguranca",
    tags: ["Relatos de problemas", "responder", "resolver", "reabrir", "excluir"],
    verNoApp: "/admin/relatos",
    corpo: [
      { t: "p", texto: "Em <strong>Administração &gt; Gestão &gt; Relatos de problemas</strong>, filtre por novo, aberto, em análise ou resolvido. Abrir um relato novo já o move para aberto." },
      { t: "passos", itens: [
        "Abra o item e confira autor, categoria, data, sala, página e contexto técnico.",
        "Reproduza com segurança e correlacione horário/sala em <strong>Sistema &gt; Logs</strong>, <strong>Dispositivos &gt; Histórico</strong> ou <strong>Sistema &gt; Status</strong>.",
        "Use <strong>Marcar em análise</strong> durante a investigação, escreva uma resposta legível ao autor e use <strong>Resolver</strong> quando houver conclusão.",
        "Use <strong>Reabrir</strong> se o problema voltar. O autor acompanha situação e resposta no próprio painel.",
      ] },
      { t: "nota", nivel: "atencao", texto: "Excluir passa por duas confirmações e remove permanentemente descrição, resposta e histórico de revisão; a auditoria preserva somente metadados da ação. A retenção automática opcional remove apenas relatos resolvidos antigos quando configurada no ambiente." },
      { t: "links", itens: [{ id: "relatos", texto: "Experiência de envio do usuário" }, { id: "auditoria", texto: "Preservação e rastreabilidade" }] },
    ],
  },
  {
    id: "auditoria",
    titulo: "Auditoria, indisponibilidade e retenção",
    papel: "superadmin",
    categoria: "super_seguranca",
    tags: ["Auditoria", "eventos", "indisponibilidade", "retenção", "histórico"],
    verNoApp: "/admin/auditoria",
    corpo: [
      { t: "p", texto: "<strong>Administração &gt; Sistema &gt; Auditoria</strong> é somente leitura. Consulte eventos administrativos por tipo, ator e alvo e períodos offline/online dos ESP32, usando intervalo de datas e paginação." },
      { t: "lista", itens: [
        "O cabeçalho mostra a retenção vigente. Eventos e indisponibilidades mais antigos são removidos automaticamente.",
        "Logs (Comandos e Acesso), Histórico de dispositivos, Sessões e Notificações mantêm históricos próprios com limites e políticas diferentes.",
        "Alteração de configuração, vínculo, credencial, relato e outras ações sensíveis deixam eventos com metadados, sem segredos.",
        "Se uma exigência institucional superar a retenção, exporte/preserve os registros autorizados fora do sistema antes da expiração.",
      ] },
      { t: "p", texto: "Para investigar uma queda: filtre a sala e o período em indisponibilidades, confira eventos administrativos próximos e então correlacione <strong>Dispositivos &gt; Histórico</strong>, <strong>Sistema &gt; Logs</strong> e as notificações." },
    ],
  },
  {
    id: "monitoramento",
    titulo: "Status e saúde do sistema",
    papel: "superadmin",
    categoria: "super_seguranca",
    tags: ["Serviço", "banco", "WAL", "disco", "backup", "falhas", "saúde"],
    verNoApp: "/admin/monitoramento",
    corpo: [
      { t: "p", texto: "<strong>Administração &gt; Sistema &gt; Status</strong> atualiza a cada 20 segundos enquanto está aberta. É diagnóstico detalhado; o <code>/health</code> continua sendo a checagem mínima de serviço e banco." },
      { t: "tabela", cabecalho: ["Cartão", "Como usar"], linhas: [
        ["Serviço", "uptime, ambiente, memória RSS, carga, Node e PID; reinício zera contadores em memória"],
        ["Banco de dados", "resposta, latência, arquivo, WAL e espaço reutilizável"],
        ["Armazenamento", "livre/total; alerta abaixo de 10% e criticidade abaixo de 5% ou 512 MiB"],
        ["Backups", "automático, quantidade, último e idade frente ao intervalo"],
        ["ESP32", "MACs, online, WebSocket, quedas, instabilidade e OTAs"],
        ["Credenciais", "provisionadas, Só MAC, revogadas e exigência global"],
        ["Históricos com limite", "uso dos limites de retenção; ≥75% merece atenção e ≥90% alerta"],
        ["Falhas desde a inicialização", "comando, telemetria, OTA, credencial, reconexão e agendador"],
      ] },
      { t: "fluxo", titulo: "Triagem de alerta", itens: [
        { tipo: "status", texto: "Identificar cartão e horário" },
        { tipo: "decision", texto: "Serviço · dados · dispositivo" },
        { tipo: "action", texto: "Correlacionar histórico" },
        { tipo: "action", texto: "Corrigir uma causa por vez" },
        { tipo: "status", texto: "Atualizar e validar normalização" },
      ] },
      { t: "nota", texto: "Alertas recorrentes viram notificações com deduplicação aproximada de seis horas. Espaço crítico dispara limpeza de retenção, mas não substitui expansão do disco nem backup externo." },
    ],
  },
  {
    id: "heatmap",
    titulo: "Mapa de calor operacional",
    papel: "superadmin",
    categoria: "super_seguranca",
    tags: ["Mapa de calor", "disponibilidade", "quedas", "comandos", "24 horas", "7 dias", "30 dias"],
    verNoApp: "/admin/monitoramento",
    corpo: [
      { t: "p", texto: "Expanda <strong>Mapa de calor operacional</strong> em <strong>Administração &gt; Sistema &gt; Status</strong>. O servidor agrega sob demanda os históricos existentes; não cria telemetria nova nem roda a consulta quando a área está fechada." },
      { t: "lista", itens: [
        "Métricas: disponibilidade, minutos offline, quedas, comandos, comandos durante offline, agendamentos criados, execuções, relatos e relatos pendentes.",
        "Períodos: 24 horas, 7 dias e 30 dias. Consultas repetidas podem usar cache de até 60 segundos.",
        "A escala fria→quente sempre ordena do melhor para o pior; em disponibilidade, porcentagem menor é pior/quente.",
        "Valor numérico, detalhe e tabela repetem a cor. A tabela ordena da pior para a melhor sala.",
        "Sem fonte confiável aparece <strong>Sem dados</strong>, nunca zero. Métricas de conectividade exigem MAC e dependem da retenção; a tela avisa quando o período a excede.",
      ] },
      { t: "nota", texto: "Use para comparar e priorizar, não para concluir causalidade." },
    ],
  },
];
