const C = require("./commands");

module.exports = [
  {
    id: "esp32-cadastro",
    titulo: "ESP32 / MACs: detectar e vincular salas",
    papel: "superadmin",
    categoria: "super_dispositivos",
    tags: ["MAC", "detectado", "vincular", "limites", "restrição"],
    verNoApp: "/admin/macs",
    corpo: [
      { t: "p", texto: "<strong>Administração &gt; ESP32 / MACs</strong> é a fonte operacional para associar uma placa a uma sala. A área separa dispositivos detectados ainda sem vínculo e as salas da planta." },
      { t: "sub", titulo: "Vincular um dispositivo detectado" },
      { t: "passos", itens: [
        "Ligue o ESP32 já configurado para alcançar o servidor e aguarde aparecer em <strong>Detectados sem sala</strong> com MAC, IP, sala informada e último contato.",
        "Confirme fisicamente qual placa e ambiente estão sendo atendidos. Selecione a sala correta e use <strong>Vincular</strong>.",
        "Confira o MAC e o estado na sala. O servidor rejeita MAC já associado a outra sala ou identificação incompatível.",
        "Use <strong>Descartar</strong> somente para remover uma detecção que não será aproveitada; a placa pode reaparecer se continuar se apresentando.",
      ] },
      { t: "sub", titulo: "Configuração por sala" },
      { t: "lista", itens: [
        "Edite ou limpe o MAC com cautela; sem associação o controlador não opera aquela sala.",
        "Limites mínimo e máximo em branco herdam os valores globais. Valores próprios precisam ficar entre 16 e 30 °C, com mínima menor que máxima; alvos e agendas fora do novo limite são ajustados.",
        "<strong>Acesso restrito</strong> exige autorização explícita de usuário comum. Prepare proprietários e acessos antes de ativar para evitar bloqueio inesperado.",
        "Quando há IP recente, a ação da interface local abre a página somente de status do ESP32; ela não substitui o portal de setup.",
      ] },
      { t: "nota", nivel: "atencao", texto: "Trocar MAC, limites ou restrição afeta a operação real. Registre a sala, preserve o vínculo anterior e valide status, controle e agendamento depois de salvar." },
      { t: "links", itens: [{ id: "esp32-setup-ap", texto: "Provisionar rede e servidor pelo setup AP" }, { id: "esp32-credenciais", texto: "Credencial exclusiva do dispositivo" }] },
    ],
  },
  {
    id: "esp32-setup-ap",
    titulo: "Setup AP permanente e provisionamento",
    papel: "superadmin",
    categoria: "super_dispositivos",
    tags: ["RemoteIFES-Setup", "192.168.4.1", "Wi-Fi", "TLS", "provisionamento", "AP permanente"],
    corpo: [
      { t: "p", texto: "A rede <strong>RemoteIFES-Setup</strong> fica no ar o tempo todo, inclusive durante a operação normal: a placa mantém AP e STA ao mesmo tempo, sem fechar o ponto de acesso quando o Wi-Fi volta. O portal local prepara Wi-Fi, servidor e, quando adotada, a credencial do ESP32, e é servido apenas pela interface desse ponto de acesso." },
      { t: "fluxo", titulo: "Provisionamento", itens: [
        { tipo: "device", texto: "ESP32 em setup AP" },
        { tipo: "action", texto: "Conectar a RemoteIFES-Setup" },
        { tipo: "screen", texto: "Abrir 192.168.4.1" },
        { tipo: "action", texto: "Wi-Fi · servidor · segurança · credencial" },
        { tipo: "device", texto: "Salvar e reiniciar" },
        { tipo: "server", texto: "Detectar, vincular MAC e validar" },
      ] },
      { t: "passos", itens: [
        "Não é preciso preparar nada para o AP aparecer: ele sobe em todo boot e permanece ativo com o dispositivo em operação.",
        "No equipamento de manutenção, conecte à rede <strong>RemoteIFES-Setup</strong> e abra <code>http://192.168.4.1</code>. Por padrão a rede é aberta; ela só pede a senha padrão do firmware (<strong>remoteifes</strong>) quando a opção global de exigir senha estiver ativada em Configurações.",
        "Informe SSID e senha da rede, host e porta do servidor. Escolha HTTPS com CA válida em produção; HTTPS sem validação ou HTTP são opções de desenvolvimento em rede controlada.",
        "Se usar credencial, informe <strong>deviceId</strong> e segredo juntos. Deixar ambos vazios preserva uma credencial já gravada.",
        "Salve. A placa reinicia, conecta ao Wi-Fi e ao WebSocket do servidor. Confirme detecção, vínculo da sala, IP e versão na aplicação.",
      ] },
      { t: "nota", nivel: "seguranca", texto: "Com o AP permanente e sem senha, qualquer pessoa ao alcance do rádio alcança o portal e pode reprovisionar a placa. Onde o acesso físico não for controlado, ative <strong>Exigir senha na rede de configuração dos ESP32</strong> em Configurações. Essa opção é do Wi-Fi local e não substitui a credencial do dispositivo no servidor; nunca registre o segredo no manual, em relato ou em log." },
      { t: "p", texto: "Se falhar, use o monitor serial para distinguir autenticação Wi-Fi, DNS/host, porta, TLS e WebSocket. O ponto de acesso continua no ar durante a falha e depois dela, então a reconfiguração local não depende do estado da rede institucional." },
    ],
  },
  {
    id: "esp32-avancado",
    titulo: "ESP32: operação avançada e infravermelho",
    papel: "superadmin",
    categoria: "super_dispositivos",
    tags: ["configuração", "clonagem", "IR", "capturar", "protocolo", "Resetar Wi-Fi"],
    verNoApp: "/admin/esp32",
    corpo: [
      { t: "p", texto: "Em <strong>Administração &gt; ESP32</strong>, cada cartão distingue Wi-Fi/telemetria do servidor e conexão WebSocket ativa, além de versão, RSSI, temperatura, protocolo IR, modo e último comando." },
      { t: "sub", titulo: "Aprender ou trocar o protocolo IR" },
      { t: "passos", itens: [
        "Selecione uma sala conectada e use <strong>Entrar em modo de configuração</strong>. Operação normal fica suspensa para essa manutenção.",
        "Use <strong>Ativar modo clonagem</strong>, aponte o controle físico ao receptor e use <strong>Iniciar captura IR</strong>. Até 20 capturas recentes ficam apenas em memória.",
        "Teste o sinal bruto capturado no aparelho correto. Se reconhecido, use a ação de adotar o protocolo detectado; então salve/valide os comandos essenciais.",
        "Use <strong>Parar captura IR</strong>, <strong>Voltar ao modo config</strong> e finalize com <strong>Sair do modo de configuração</strong>.",
        "No painel comum, valide Power, temperaturas-limite e Turbo. Consulte Logs para confirmar o caminho do comando.",
      ] },
      { t: "p", texto: "O modo de clonagem é temporário e não deve permanecer ativo. Captura ou teste errado pode acionar outro aparelho; isole o ambiente e trabalhe com uma sala por vez." },
      { t: "sub", titulo: "Resetar Wi-Fi" },
      { t: "nota", nivel: "atencao", texto: "<strong>Resetar Wi-Fi</strong> apaga rede e endereço do servidor da NVS e reinicia a placa; RemoteIFES-Setup já estava no ar e continua. A credencial exclusiva do dispositivo é preservada. Tenha acesso físico e os dados corretos antes de confirmar." },
    ],
  },
  {
    id: "ota-credenciais",
    titulo: "OTA e credenciais: visão geral segura",
    papel: "superadmin",
    categoria: "super_dispositivos",
    tags: ["OTA", "credencial", "firmware", "segredo"],
    verNoApp: "/admin/esp32",
    corpo: [
      { t: "p", texto: "A atualização OTA e a identidade por credencial são controles separados: OTA distribui uma imagem de firmware publicada; a credencial autentica a placa. Ambos são exclusivos do Superadministrador." },
      { t: "fluxo", titulo: "Relação entre as operações", itens: [
        { tipo: "server", texto: "Publicar firmware + SHA-256" },
        { tipo: "role", texto: "Superadministrador oferece OTA" },
        { tipo: "device", texto: "ESP32 autenticado baixa e valida" },
        { tipo: "status", texto: "Reinício: concluiu, falhou ou reverteu" },
      ] },
      { t: "links", titulo: "Procedimentos completos", itens: [{ id: "firmware-ota", texto: "Publicar e acompanhar OTA" }, { id: "esp32-credenciais", texto: "Provisionar, rotacionar, substituir ou revogar" }] },
    ],
  },
  {
    id: "esp32-credenciais",
    titulo: "Credenciais exclusivas de ESP32",
    papel: "superadmin",
    categoria: "super_dispositivos",
    tags: ["provisionar", "rotacionar", "substituir", "revogar", "deviceId"],
    verNoApp: "/admin/esp32",
    corpo: [
      { t: "tabela", cabecalho: ["Ação", "Efeito e uso"], linhas: [
        ["Provisionar", "cria deviceId e segredo; a sala passa a exigir a credencial, mesmo antes da exigência global"],
        ["Rotacionar", "mantém deviceId, cria segredo novo e aceita o anterior por 24 horas para transição"],
        ["Substituir", "cria nova identidade para outra placa, invalida e desconecta a antiga imediatamente"],
        ["Revogar", "invalida a identidade e encerra a conexão; exige novo provisionamento para voltar"],
      ] },
      { t: "p", texto: "Provisionar ou rotacionar envia o novo valor automaticamente a uma placa ainda conectada pelo vínculo atual. Substituir nunca envia a identidade nova à placa antiga: informe-a no setup da substituta. O servidor guarda somente o hash e mostra o segredo uma única vez." },
      { t: "comando", titulo: "Gerenciar no host", comandos: C.credenciais, quando: "Quando a interface não estiver disponível ou a operação fizer parte de uma janela controlada.", preRequisitos: "Execute em remoteifes-server, com o mesmo .env e diretório de dados do serviço; troque A-101 pela sala real.", resultado: "O estado é exibido sem segredo; ações de criação mostram deviceId e segredo somente nessa execução.", risco: "Capture o segredo em canal seguro. Substituir ou revogar derruba a identidade anterior." },
      { t: "sub", titulo: "Migração de só MAC" },
      { t: "passos", itens: [
        "Mantenha <strong>Exigir credencial por dispositivo em todos os ESP32</strong> desligado.",
        "Provisione e valide cada sala; acompanhe <strong>Só MAC</strong> em Monitoramento.",
        "Quando todas estiverem autenticadas, ative a exigência global e confirme que nenhuma sala caiu.",
        "Em falha ampla, desative temporariamente a exigência, corrija as salas e refaça a validação.",
      ] },
    ],
  },
  {
    id: "firmware-usb",
    titulo: "Firmware por USB e recuperação do ESP32",
    papel: "superadmin",
    categoria: "super_dispositivos",
    tags: ["PlatformIO", "flash", "LittleFS", "serial", "erase"],
    corpo: [
      { t: "comando", titulo: "Fluxo automatizado", comandos: C.firmwareUsb.slice(0, 3), quando: "Primeira gravação, atualização local ou recuperação que não depende de OTA.", preRequisitos: "PlatformIO ou capacidade do flash.sh de instalá-lo; cabo USB de dados; permissão na porta serial.", resultado: "Compila, grava data/ em LittleFS e grava o firmware; com várias portas, informe a porta explicitamente.", risco: "O fluxo automatizado não apaga a flash inteira, mas substitui firmware e LittleFS." },
      { t: "comando", titulo: "Passos manuais do PlatformIO", comandos: C.firmwareUsb.slice(3), quando: "Diagnóstico fino, gravação por etapas ou monitor serial.", preRequisitos: "Execute em remoteifes-esp32; selecione a porta com -p quando necessário.", resultado: "Compilação, gravação de arquivos, gravação da aplicação ou logs a 115200 baud, conforme a linha.", risco: "pio run --target erase apaga toda a flash, inclusive rede e configuração; use só quando a limpeza total for intencional." },
      { t: "passos", itens: [
        "Antes de erase, registre sala/MAC e garanta dados de rede, servidor e credencial para reprovisionar.",
        "Após gravar, acompanhe o boot no monitor serial e procure versão, Wi-Fi e WebSocket.",
        "Refaça setup AP e vínculo se foram apagados; depois valide controle e telemetria.",
      ] },
      { t: "nota", texto: "A gravação USB é a recuperação de referência quando OTA não inicia ou reverte repetidamente. Ela regrava o slot ativo sem depender do servidor." },
    ],
  },
  {
    id: "firmware-ota",
    titulo: "Publicar e acompanhar firmware OTA",
    papel: "superadmin",
    categoria: "super_dispositivos",
    tags: ["firmware", "OTA", "SHA-256", "versão", "rollback"],
    verNoApp: "/admin/esp32",
    corpo: [
      { t: "comando", titulo: "Compilar e publicar a imagem", comandos: C.firmwareOta, quando: "Depois de validar o firmware e antes de oferecer OTA às salas.", preRequisitos: "PlatformIO; execute as duas últimas linhas em remoteifes-server; a versão deve corresponder ao firmware e seguir x.y.z.", resultado: "firmware.bin válido (64 KiB–3 MiB), SHA-256 e manifesto atômico passam a representar a única versão publicada.", risco: "Publicar troca a oferta para todos; valide em bancada e preserve o caminho USB de recuperação." },
      { t: "passos", itens: [
        "Em <strong>Administração &gt; ESP32</strong>, compare a versão publicada com a instalada e escolha primeiro uma sala piloto conectada.",
        "Use a ação OTA. O servidor limita a duas atualizações simultâneas e recusa downgrade, versão já instalada ou uma segunda operação na mesma sala.",
        "Acompanhe ofertado, baixando, gravado e reiniciando. A conclusão exige a placa voltar e reportar a versão nova; falha ou versão antiga indica erro/reversão.",
        "Valide conexão, telemetria e comandos na sala piloto antes de avançar em lotes pequenos.",
      ] },
      { t: "p", texto: "O ESP32 confere tamanho e SHA-256 antes de gravar. A imagem usa partições A/B e tem até 90 segundos após iniciar para validar Wi-Fi e WebSocket; se isso falhar, o bootloader reverte. O servidor mantém o estado por reinício e aplica timeouts de transferência e retorno." },
      { t: "nota", nivel: "atencao", texto: "OTA preserva NVS e vínculo da sala, mas sempre pode exigir recuperação física. Não atualize todos os dispositivos ao mesmo tempo e não desligue energia durante download/gravação." },
      { t: "links", itens: [{ id: "firmware-usb", texto: "Recuperar por USB" }, { id: "monitoramento", texto: "Investigar falha e notificações" }] },
    ],
  },
];
