module.exports = [
  {
    id: "configuracoes-globais",
    titulo: "Configurações globais",
    papel: "superadmin",
    categoria: "super_seguranca",
    tags: ["Configurações", "sessão", "temperatura", "Turbo", "Auto-ON", "modo de teste", "manutenção", "retenção", "RemoteIFES-Setup"],
    verNoApp: "/admin/config",
    corpo: [
      { t: "p", texto: "<strong>Administração &gt; Sistema &gt; Configurações</strong> aplica política global. Leia todos os campos e registre os valores anteriores antes de salvar." },
      { t: "tabela", cabecalho: ["Grupo", "Efeito"], linhas: [
        ["Sessão por inatividade", "prazos distintos para usuários e administradores e antecedência do aviso"],
        ["Presença online", "tempo sem uso ainda classificado como online em Sistema > Status > Usuários ativos"],
        ["Limite de temperatura", "faixa global 16–30 °C; alvos e agendas fora da nova faixa são ajustados"],
        ["Função adicional do Turbo", "nenhuma ou Oscilação vertical (Swing), aplicada junto do Turbo"],
        ["Auto-ON", "ligado por padrão: ajustar a temperatura ou ativar o Turbo em um aparelho desligado o liga e aplica o ajuste; desligado, a temperatura só é guardada e o Turbo exige aparelho ligado"],
        ["Modo de teste", "desativa temporariamente a restrição de rede em produção"],
        ["Redes autorizadas", "uma faixa CIDR por linha para acesso normal em produção"],
        ["Modo de manutenção", "bloqueia login e uso de usuários comuns; administradores continuam"],
        ["Credenciais obrigatórias", "recusa todo ESP32 que ainda se autentique somente por MAC"],
        ["Senha na rede RemoteIFES-Setup", "desligada por padrão: o AP de configuração do ESP32, que só existe durante o provisionamento ou após o clique no switch, fica aberto. Ligada, ele passa a exigir a senha padrão do firmware. Só afeta o Wi-Fi local, não a autenticação no servidor"],
        ["Retenção", "1–365 dias para auditoria e indisponibilidade; limpeza é automática"],
      ] },
      { t: "passos", itens: [
        "Confirme a janela operacional e o impacto nos usuários/dispositivos.",
        "Altere apenas o grupo necessário e use <strong>Salvar configurações</strong>.",
        "Espere <strong>Configurações salvas</strong>. Mudanças de temperatura/Turbo propagam o estado desejado aos dispositivos configurados; Auto-ON vale imediatamente para todos os painéis; sessões recebem o novo prazo.",
        "Valide Início, uma sala piloto, <strong>Sistema &gt; Status &gt; Usuários ativos</strong> e <strong>Sistema &gt; Status &gt; Sistema</strong>. Em falha, restaure os valores registrados e salve novamente.",
      ] },
      { t: "nota", nivel: "seguranca", texto: "Modo de teste pode expor o sistema fora das redes autorizadas; use apenas durante um teste supervisionado e desligue em seguida. Não ative credenciais obrigatórias enquanto o Status ainda mostrar salas Só MAC. A senha do RemoteIFES-Setup é um controle separado: ative-a onde o acesso físico às salas não for controlado." },
      { t: "links", itens: [{ id: "esp32-credenciais", texto: "Migrar credenciais antes da exigência global" }, { id: "servidor-rede", texto: "Rede, proxy e HTTPS no host" }] },
    ],
  },
  {
    id: "relatos-gestao",
    titulo: "Gerenciar relatos de problemas",
    papel: "superadmin",
    categoria: "super_seguranca",
    tags: ["Relatos de problemas", "responder", "resolver", "reabrir", "excluir"],
    verNoApp: "/admin/relatos",
    corpo: [
      { t: "p", texto: "Em <strong>Administração &gt; Gestão &gt; Relatos de problemas</strong>, filtre por novo, aberto, em análise ou resolvido. Abrir um relato novo já o move para aberto." },
      { t: "passos", itens: [
        "Abra o item e confira autor, categoria, data, sala, página e contexto técnico.",
        "Reproduza com segurança e correlacione horário/sala em <strong>Sistema &gt; Logs</strong> ou <strong>Sistema &gt; Status</strong>.",
        "Use <strong>Marcar em análise</strong> durante a investigação, escreva uma resposta legível ao autor e use <strong>Resolver</strong> quando houver conclusão.",
        "Use <strong>Reabrir</strong> se o problema voltar. O autor acompanha situação e resposta no próprio painel.",
      ] },
      { t: "nota", nivel: "atencao", texto: "Excluir passa por duas confirmações e remove permanentemente descrição, resposta e histórico de revisão; a auditoria preserva somente metadados da ação. A retenção automática opcional remove apenas relatos resolvidos antigos quando configurada no ambiente." },
      { t: "links", itens: [{ id: "relatos", texto: "Experiência de envio do usuário" }, { id: "auditoria", texto: "Preservação e rastreabilidade" }] },
    ],
  },
  {
    id: "auditoria",
    titulo: "Auditoria, indisponibilidade e retenção",
    papel: "superadmin",
    categoria: "super_seguranca",
    tags: ["Auditoria", "eventos", "indisponibilidade", "retenção", "histórico"],
    verNoApp: "/admin/logs/auditoria",
    corpo: [
      { t: "p", texto: "<strong>Administração &gt; Sistema &gt; Logs &gt; Auditoria</strong> é somente leitura. Consulte eventos administrativos por tipo, ator e alvo e períodos offline/online dos ESP32, usando intervalo de datas e paginação." },
      { t: "lista", itens: [
        "O cabeçalho mostra a retenção vigente. Eventos e indisponibilidades mais antigos são removidos automaticamente.",
        "As outras abas de Logs — Comandos, Acessos, Dispositivos e Sessões — e a fila de Alertas mantêm históricos próprios, com limites e políticas de retenção diferentes.",
        "Alteração de configuração, vínculo, credencial, relato e outras ações sensíveis deixam eventos com metadados, sem segredos.",
        "Se uma exigência institucional superar a retenção, exporte/preserve os registros autorizados fora do sistema antes da expiração.",
      ] },
      { t: "p", texto: "Para investigar uma queda: filtre a sala e o período em indisponibilidades, confira eventos administrativos próximos e então correlacione <strong>Sistema &gt; Logs &gt; Dispositivos</strong>, <strong>Sistema &gt; Logs &gt; Comandos</strong> e os alertas." },
    ],
  },
  {
    id: "monitoramento",
    titulo: "Status e saúde do sistema",
    papel: "superadmin",
    categoria: "super_seguranca",
    tags: ["Serviço", "banco", "WAL", "disco", "backup", "falhas", "saúde"],
    verNoApp: "/admin/status/sistema",
    corpo: [
      { t: "p", texto: "<strong>Administração &gt; Sistema &gt; Status &gt; Sistema</strong> atualiza a cada 20 segundos enquanto está aberta. É diagnóstico detalhado; o <code>/health</code> continua sendo a checagem mínima de serviço e banco." },
      { t: "tabela", cabecalho: ["Cartão", "Como usar"], linhas: [
        ["Serviço", "uptime, ambiente, memória RSS, carga, Node e PID (e nome, modo e reinícios quando roda sob PM2); reinício zera contadores em memória"],
        ["Banco de dados", "resposta, latência, arquivo, WAL e espaço reutilizável"],
        ["Armazenamento", "livre/total; alerta abaixo de 10% e criticidade abaixo de 5% ou 512 MiB"],
        ["Backups", "automático, quantidade, último e idade frente ao intervalo"],
        ["ESP32", "MACs, online, WebSocket, quedas, instabilidade e OTAs"],
        ["Credenciais", "provisionadas, Só MAC, revogadas e exigência global"],
        ["Históricos com limite", "uso dos limites de retenção, inclusive das amostras e horas do histórico de monitoramento; ≥75% merece atenção e ≥90% alerta"],
        ["Falhas desde a inicialização", "comando, telemetria, OTA, credencial, reconexão e agendador"],
      ] },
      { t: "fluxo", titulo: "Triagem de alerta", itens: [
        { tipo: "status", texto: "Identificar cartão e horário" },
        { tipo: "decision", texto: "Serviço · dados · dispositivo" },
        { tipo: "action", texto: "Correlacionar histórico" },
        { tipo: "action", texto: "Corrigir uma causa por vez" },
        { tipo: "status", texto: "Atualizar e validar normalização" },
      ] },
      { t: "nota", texto: "Alertas recorrentes viram notificações com deduplicação aproximada de seis horas. Espaço crítico dispara limpeza de retenção, mas não substitui expansão do disco nem backup externo." },
      { t: "links", itens: [{ id: "graficos", texto: "Histórico e gráficos" }, { id: "heatmap", texto: "Mapa de calor operacional" }] },
    ],
  },
  {
    id: "heatmap",
    titulo: "Mapa de calor operacional",
    papel: "superadmin",
    categoria: "super_seguranca",
    tags: ["Mapa de calor", "disponibilidade", "quedas", "comandos", "24 horas", "7 dias", "30 dias"],
    verNoApp: "/admin/status/sistema",
    corpo: [
      { t: "p", texto: "Expanda <strong>Mapa de calor operacional</strong> em <strong>Administração &gt; Sistema &gt; Status &gt; Sistema</strong>. O servidor agrega sob demanda os históricos existentes; não cria telemetria nova nem roda a consulta quando a área está fechada." },
      { t: "lista", itens: [
        "Métricas: disponibilidade, minutos offline, quedas, comandos, comandos durante offline, agendamentos criados, execuções, relatos e relatos pendentes.",
        "Períodos: 24 horas, 7 dias e 30 dias. Consultas repetidas podem usar cache de até 60 segundos.",
        "A escala fria→quente sempre ordena do melhor para o pior; em disponibilidade, porcentagem menor é pior/quente.",
        "Valor numérico, detalhe e tabela repetem a cor. A tabela ordena da pior para a melhor sala.",
        "Sem fonte confiável aparece <strong>Sem dados</strong>, nunca zero. Métricas de conectividade exigem MAC e dependem da retenção; a tela avisa quando o período a excede.",
      ] },
      { t: "nota", texto: "Use para comparar e priorizar, não para concluir causalidade." },
    ],
  },
  {
    id: "graficos",
    titulo: "Histórico e gráficos do monitoramento",
    papel: "superadmin",
    categoria: "super_seguranca",
    tags: ["gráficos", "histórico", "RSS", "CPU", "latência", "disco", "reconexões", "falhas", "comandos", "3 horas", "24 horas", "7 dias", "30 dias", "PM2"],
    verNoApp: "/admin/status/sistema",
    corpo: [
      { t: "p", texto: "A seção <strong>Histórico e gráficos</strong>, em <strong>Administração &gt; Sistema &gt; Status &gt; Sistema</strong>, transforma os cartões em um painel de tendências. Os cartões continuam sendo a leitura exata e atualizada a cada 20 segundos; os gráficos mostram a evolução e só são consultados com a seção aberta (a preferência de recolher fica no navegador)." },
      { t: "tabela", cabecalho: ["Gráfico", "Forma e leitura"], linhas: [
        ["ESP32 conectados", "linhas: com MAC, online e conectados por WebSocket; a diferença entre elas é o offline inesperado"],
        ["Reconexões e quedas", "colunas agrupadas por intervalo, a partir dos eventos online/offline já registrados em Logs &gt; Dispositivos"],
        ["Falhas por período", "colunas empilhadas: telemetria, credencial, agendador e banco (deltas por intervalo) e OTA (notificações de falha)"],
        ["Comandos por período", "colunas empilhadas por origem: manual, agendamento, ESP32 local e outros"],
        ["Memória RSS · CPU · Latência do banco", "área da média com linha de pico por intervalo; CPU em percentual de um núcleo"],
        ["Arquivo do banco e WAL · Disco livre", "linhas de tamanho; disco livre mostra o mínimo do intervalo"],
        ["ESP32 online e offline · Credenciais · OTA por fase", "roscas com a composição atual, número central e legenda com quantidade e percentual"],
        ["Uso dos históricos com limite", "barras horizontais com o uso de cada tabela limitada, incluindo as duas tabelas do próprio histórico"],
      ] },
      { t: "lista", itens: [
        "Amostragem: o servidor grava uma amostra por minuto fora do caminho de comandos, telemetria e WebSocket (memória, CPU do processo, carga, latência e tamanho do banco/WAL, disco, contagens de ESP32 e deltas dos contadores de falha).",
        "Retenção: amostras brutas por 48 horas e médias/picos por hora por 30 dias, consolidadas a cada minuto e limpas pela rotina de retenção (limites de 6 000 e 1 000 linhas); a tabela de uso mostra o próprio crescimento.",
        "Faixas: 3 horas (3 min por ponto) e 24 horas (15 min) vêm das amostras; 7 dias (1 h) e 30 dias (6 h) vêm das horas consolidadas mais a hora corrente. Nada além de 168 pontos é enviado ao navegador.",
        "Reinícios: cada início de processo aparece como marcador; nas faixas longas ele é aproximado à hora. Intervalos sem amostra ficam em branco, sem interpolação; contadores em memória nunca são exibidos como acumulado no gráfico.",
        "Leitura sem cor: toda figura tem legenda, resumo em texto, leitura por teclado (setas, Home, End, Esc), toque ou passagem do ponteiro e <strong>Ver tabela de valores</strong>. O alto contraste troca a paleta.",
        "PM2 (opcional): quando o servidor roda sob PM2, o cartão Serviço mostra nome, modo e reinícios informados pelo gerenciador; sem PM2 nada é inventado.",
      ] },
      { t: "nota", texto: "Cobertura parcial (instalação recente ou período maior que a retenção) é avisada acima dos gráficos. O histórico sobrevive a reinícios do servidor; apenas os contadores em memória recomeçam." },
    ],
  },
];
